/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.AcaoJudicialProposta;
import br.com.seatecnologia.gdf.negocia.model.AcaoJudicialPropostaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AcaoJudicialProposta service. Represents a row in the &quot;GDF_AcaoJudicialProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AcaoJudicialPropostaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AcaoJudicialPropostaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AcaoJudicialPropostaImpl
 * @generated
 */
@JSON(strict = true)
public class AcaoJudicialPropostaModelImpl
	extends BaseModelImpl<AcaoJudicialProposta>
	implements AcaoJudicialPropostaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a acao judicial proposta model instance should use the <code>AcaoJudicialProposta</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_AcaoJudicialProposta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"acaoPropostaId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"acaoId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("acaoPropostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("acaoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_AcaoJudicialProposta (uuid_ VARCHAR(75) null,acaoPropostaId LONG not null primary key,propostaId LONG,acaoId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_AcaoJudicialProposta";

	public static final String ORDER_BY_JPQL =
		" ORDER BY acaoJudicialProposta.acaoPropostaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_AcaoJudicialProposta.acaoPropostaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACAOPROPOSTAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AcaoJudicialPropostaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _acaoPropostaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAcaoPropostaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _acaoPropostaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AcaoJudicialProposta.class;
	}

	@Override
	public String getModelClassName() {
		return AcaoJudicialProposta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AcaoJudicialProposta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AcaoJudicialProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AcaoJudicialProposta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AcaoJudicialProposta)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AcaoJudicialProposta, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AcaoJudicialProposta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AcaoJudicialProposta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AcaoJudicialProposta, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AcaoJudicialProposta, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AcaoJudicialProposta, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AcaoJudicialProposta, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AcaoJudicialProposta, Object>>();

			attributeGetterFunctions.put("uuid", AcaoJudicialProposta::getUuid);
			attributeGetterFunctions.put(
				"acaoPropostaId", AcaoJudicialProposta::getAcaoPropostaId);
			attributeGetterFunctions.put(
				"propostaId", AcaoJudicialProposta::getPropostaId);
			attributeGetterFunctions.put(
				"acaoId", AcaoJudicialProposta::getAcaoId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AcaoJudicialProposta, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AcaoJudicialProposta, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AcaoJudicialProposta, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AcaoJudicialProposta, String>)
					AcaoJudicialProposta::setUuid);
			attributeSetterBiConsumers.put(
				"acaoPropostaId",
				(BiConsumer<AcaoJudicialProposta, Long>)
					AcaoJudicialProposta::setAcaoPropostaId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<AcaoJudicialProposta, Long>)
					AcaoJudicialProposta::setPropostaId);
			attributeSetterBiConsumers.put(
				"acaoId",
				(BiConsumer<AcaoJudicialProposta, Long>)
					AcaoJudicialProposta::setAcaoId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAcaoPropostaId() {
		return _acaoPropostaId;
	}

	@Override
	public void setAcaoPropostaId(long acaoPropostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acaoPropostaId = acaoPropostaId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public long getAcaoId() {
		return _acaoId;
	}

	@Override
	public void setAcaoId(long acaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acaoId = acaoId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AcaoJudicialProposta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AcaoJudicialProposta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AcaoJudicialProposta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AcaoJudicialPropostaImpl acaoJudicialPropostaImpl =
			new AcaoJudicialPropostaImpl();

		acaoJudicialPropostaImpl.setUuid(getUuid());
		acaoJudicialPropostaImpl.setAcaoPropostaId(getAcaoPropostaId());
		acaoJudicialPropostaImpl.setPropostaId(getPropostaId());
		acaoJudicialPropostaImpl.setAcaoId(getAcaoId());

		acaoJudicialPropostaImpl.resetOriginalValues();

		return acaoJudicialPropostaImpl;
	}

	@Override
	public AcaoJudicialProposta cloneWithOriginalValues() {
		AcaoJudicialPropostaImpl acaoJudicialPropostaImpl =
			new AcaoJudicialPropostaImpl();

		acaoJudicialPropostaImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		acaoJudicialPropostaImpl.setAcaoPropostaId(
			this.<Long>getColumnOriginalValue("acaoPropostaId"));
		acaoJudicialPropostaImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		acaoJudicialPropostaImpl.setAcaoId(
			this.<Long>getColumnOriginalValue("acaoId"));

		return acaoJudicialPropostaImpl;
	}

	@Override
	public int compareTo(AcaoJudicialProposta acaoJudicialProposta) {
		long primaryKey = acaoJudicialProposta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AcaoJudicialProposta)) {
			return false;
		}

		AcaoJudicialProposta acaoJudicialProposta =
			(AcaoJudicialProposta)object;

		long primaryKey = acaoJudicialProposta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AcaoJudicialProposta> toCacheModel() {
		AcaoJudicialPropostaCacheModel acaoJudicialPropostaCacheModel =
			new AcaoJudicialPropostaCacheModel();

		acaoJudicialPropostaCacheModel.uuid = getUuid();

		String uuid = acaoJudicialPropostaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			acaoJudicialPropostaCacheModel.uuid = null;
		}

		acaoJudicialPropostaCacheModel.acaoPropostaId = getAcaoPropostaId();

		acaoJudicialPropostaCacheModel.propostaId = getPropostaId();

		acaoJudicialPropostaCacheModel.acaoId = getAcaoId();

		return acaoJudicialPropostaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AcaoJudicialProposta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AcaoJudicialProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AcaoJudicialProposta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AcaoJudicialProposta)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AcaoJudicialProposta>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AcaoJudicialProposta.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _acaoPropostaId;
	private long _propostaId;
	private long _acaoId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AcaoJudicialProposta, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AcaoJudicialProposta)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("acaoPropostaId", _acaoPropostaId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("acaoId", _acaoId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("acaoPropostaId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("acaoId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AcaoJudicialProposta _escapedModel;

}