/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.AcaoJudicial;
import br.com.seatecnologia.gdf.negocia.service.AcaoJudicialLocalServiceUtil;

/**
 * The extended model base implementation for the AcaoJudicial service. Represents a row in the &quot;GDF_AcaoJudicial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AcaoJudicialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AcaoJudicialImpl
 * @see AcaoJudicial
 * @generated
 */
public abstract class AcaoJudicialBaseImpl
	extends AcaoJudicialModelImpl implements AcaoJudicial {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a acao judicial model instance should use the <code>AcaoJudicial</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AcaoJudicialLocalServiceUtil.addAcaoJudicial(this);
		}
		else {
			AcaoJudicialLocalServiceUtil.updateAcaoJudicial(this);
		}
	}

}