/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.AdministradorJudicial;
import br.com.seatecnologia.gdf.negocia.model.AdministradorJudicialModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AdministradorJudicial service. Represents a row in the &quot;GDF_AdministradorJudicial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AdministradorJudicialModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdministradorJudicialImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdministradorJudicialImpl
 * @generated
 */
@JSON(strict = true)
public class AdministradorJudicialModelImpl
	extends BaseModelImpl<AdministradorJudicial>
	implements AdministradorJudicialModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a administrador judicial model instance should use the <code>AdministradorJudicial</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_AdministradorJudicial";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"administradorJudicialId", Types.BIGINT},
		{"qualificacaoId", Types.BIGINT}, {"regimeFalencia", Types.BOOLEAN},
		{"recuperacao", Types.VARCHAR}, {"numeroProcesso", Types.VARCHAR},
		{"anexoRecuperacao", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("administradorJudicialId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("qualificacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("regimeFalencia", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("recuperacao", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("numeroProcesso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anexoRecuperacao", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_AdministradorJudicial (uuid_ VARCHAR(75) null,administradorJudicialId LONG not null primary key,qualificacaoId LONG,regimeFalencia BOOLEAN,recuperacao VARCHAR(255) null,numeroProcesso VARCHAR(255) null,anexoRecuperacao LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_AdministradorJudicial";

	public static final String ORDER_BY_JPQL =
		" ORDER BY administradorJudicial.administradorJudicialId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_AdministradorJudicial.administradorJudicialId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADMINISTRADORJUDICIALID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AdministradorJudicialModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _administradorJudicialId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAdministradorJudicialId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _administradorJudicialId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AdministradorJudicial.class;
	}

	@Override
	public String getModelClassName() {
		return AdministradorJudicial.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AdministradorJudicial, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AdministradorJudicial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AdministradorJudicial, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AdministradorJudicial)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AdministradorJudicial, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AdministradorJudicial, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AdministradorJudicial)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AdministradorJudicial, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AdministradorJudicial, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AdministradorJudicial, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AdministradorJudicial, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AdministradorJudicial, Object>>();

			attributeGetterFunctions.put(
				"uuid", AdministradorJudicial::getUuid);
			attributeGetterFunctions.put(
				"administradorJudicialId",
				AdministradorJudicial::getAdministradorJudicialId);
			attributeGetterFunctions.put(
				"qualificacaoId", AdministradorJudicial::getQualificacaoId);
			attributeGetterFunctions.put(
				"regimeFalencia", AdministradorJudicial::getRegimeFalencia);
			attributeGetterFunctions.put(
				"recuperacao", AdministradorJudicial::getRecuperacao);
			attributeGetterFunctions.put(
				"numeroProcesso", AdministradorJudicial::getNumeroProcesso);
			attributeGetterFunctions.put(
				"anexoRecuperacao", AdministradorJudicial::getAnexoRecuperacao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AdministradorJudicial, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AdministradorJudicial, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AdministradorJudicial, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AdministradorJudicial, String>)
					AdministradorJudicial::setUuid);
			attributeSetterBiConsumers.put(
				"administradorJudicialId",
				(BiConsumer<AdministradorJudicial, Long>)
					AdministradorJudicial::setAdministradorJudicialId);
			attributeSetterBiConsumers.put(
				"qualificacaoId",
				(BiConsumer<AdministradorJudicial, Long>)
					AdministradorJudicial::setQualificacaoId);
			attributeSetterBiConsumers.put(
				"regimeFalencia",
				(BiConsumer<AdministradorJudicial, Boolean>)
					AdministradorJudicial::setRegimeFalencia);
			attributeSetterBiConsumers.put(
				"recuperacao",
				(BiConsumer<AdministradorJudicial, String>)
					AdministradorJudicial::setRecuperacao);
			attributeSetterBiConsumers.put(
				"numeroProcesso",
				(BiConsumer<AdministradorJudicial, String>)
					AdministradorJudicial::setNumeroProcesso);
			attributeSetterBiConsumers.put(
				"anexoRecuperacao",
				(BiConsumer<AdministradorJudicial, Long>)
					AdministradorJudicial::setAnexoRecuperacao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAdministradorJudicialId() {
		return _administradorJudicialId;
	}

	@Override
	public void setAdministradorJudicialId(long administradorJudicialId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_administradorJudicialId = administradorJudicialId;
	}

	@JSON
	@Override
	public long getQualificacaoId() {
		return _qualificacaoId;
	}

	@Override
	public void setQualificacaoId(long qualificacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qualificacaoId = qualificacaoId;
	}

	@JSON
	@Override
	public boolean getRegimeFalencia() {
		return _regimeFalencia;
	}

	@JSON
	@Override
	public boolean isRegimeFalencia() {
		return _regimeFalencia;
	}

	@Override
	public void setRegimeFalencia(boolean regimeFalencia) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_regimeFalencia = regimeFalencia;
	}

	@JSON
	@Override
	public String getRecuperacao() {
		if (_recuperacao == null) {
			return "";
		}
		else {
			return _recuperacao;
		}
	}

	@Override
	public void setRecuperacao(String recuperacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recuperacao = recuperacao;
	}

	@JSON
	@Override
	public String getNumeroProcesso() {
		if (_numeroProcesso == null) {
			return "";
		}
		else {
			return _numeroProcesso;
		}
	}

	@Override
	public void setNumeroProcesso(String numeroProcesso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numeroProcesso = numeroProcesso;
	}

	@JSON
	@Override
	public long getAnexoRecuperacao() {
		return _anexoRecuperacao;
	}

	@Override
	public void setAnexoRecuperacao(long anexoRecuperacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anexoRecuperacao = anexoRecuperacao;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AdministradorJudicial.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AdministradorJudicial toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AdministradorJudicial>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AdministradorJudicialImpl administradorJudicialImpl =
			new AdministradorJudicialImpl();

		administradorJudicialImpl.setUuid(getUuid());
		administradorJudicialImpl.setAdministradorJudicialId(
			getAdministradorJudicialId());
		administradorJudicialImpl.setQualificacaoId(getQualificacaoId());
		administradorJudicialImpl.setRegimeFalencia(isRegimeFalencia());
		administradorJudicialImpl.setRecuperacao(getRecuperacao());
		administradorJudicialImpl.setNumeroProcesso(getNumeroProcesso());
		administradorJudicialImpl.setAnexoRecuperacao(getAnexoRecuperacao());

		administradorJudicialImpl.resetOriginalValues();

		return administradorJudicialImpl;
	}

	@Override
	public AdministradorJudicial cloneWithOriginalValues() {
		AdministradorJudicialImpl administradorJudicialImpl =
			new AdministradorJudicialImpl();

		administradorJudicialImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		administradorJudicialImpl.setAdministradorJudicialId(
			this.<Long>getColumnOriginalValue("administradorJudicialId"));
		administradorJudicialImpl.setQualificacaoId(
			this.<Long>getColumnOriginalValue("qualificacaoId"));
		administradorJudicialImpl.setRegimeFalencia(
			this.<Boolean>getColumnOriginalValue("regimeFalencia"));
		administradorJudicialImpl.setRecuperacao(
			this.<String>getColumnOriginalValue("recuperacao"));
		administradorJudicialImpl.setNumeroProcesso(
			this.<String>getColumnOriginalValue("numeroProcesso"));
		administradorJudicialImpl.setAnexoRecuperacao(
			this.<Long>getColumnOriginalValue("anexoRecuperacao"));

		return administradorJudicialImpl;
	}

	@Override
	public int compareTo(AdministradorJudicial administradorJudicial) {
		long primaryKey = administradorJudicial.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AdministradorJudicial)) {
			return false;
		}

		AdministradorJudicial administradorJudicial =
			(AdministradorJudicial)object;

		long primaryKey = administradorJudicial.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AdministradorJudicial> toCacheModel() {
		AdministradorJudicialCacheModel administradorJudicialCacheModel =
			new AdministradorJudicialCacheModel();

		administradorJudicialCacheModel.uuid = getUuid();

		String uuid = administradorJudicialCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			administradorJudicialCacheModel.uuid = null;
		}

		administradorJudicialCacheModel.administradorJudicialId =
			getAdministradorJudicialId();

		administradorJudicialCacheModel.qualificacaoId = getQualificacaoId();

		administradorJudicialCacheModel.regimeFalencia = isRegimeFalencia();

		administradorJudicialCacheModel.recuperacao = getRecuperacao();

		String recuperacao = administradorJudicialCacheModel.recuperacao;

		if ((recuperacao != null) && (recuperacao.length() == 0)) {
			administradorJudicialCacheModel.recuperacao = null;
		}

		administradorJudicialCacheModel.numeroProcesso = getNumeroProcesso();

		String numeroProcesso = administradorJudicialCacheModel.numeroProcesso;

		if ((numeroProcesso != null) && (numeroProcesso.length() == 0)) {
			administradorJudicialCacheModel.numeroProcesso = null;
		}

		administradorJudicialCacheModel.anexoRecuperacao =
			getAnexoRecuperacao();

		return administradorJudicialCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AdministradorJudicial, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AdministradorJudicial, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AdministradorJudicial, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AdministradorJudicial)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AdministradorJudicial>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AdministradorJudicial.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _administradorJudicialId;
	private long _qualificacaoId;
	private boolean _regimeFalencia;
	private String _recuperacao;
	private String _numeroProcesso;
	private long _anexoRecuperacao;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AdministradorJudicial, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AdministradorJudicial)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"administradorJudicialId", _administradorJudicialId);
		_columnOriginalValues.put("qualificacaoId", _qualificacaoId);
		_columnOriginalValues.put("regimeFalencia", _regimeFalencia);
		_columnOriginalValues.put("recuperacao", _recuperacao);
		_columnOriginalValues.put("numeroProcesso", _numeroProcesso);
		_columnOriginalValues.put("anexoRecuperacao", _anexoRecuperacao);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("administradorJudicialId", 2L);

		columnBitmasks.put("qualificacaoId", 4L);

		columnBitmasks.put("regimeFalencia", 8L);

		columnBitmasks.put("recuperacao", 16L);

		columnBitmasks.put("numeroProcesso", 32L);

		columnBitmasks.put("anexoRecuperacao", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AdministradorJudicial _escapedModel;

}