/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Advogado;
import br.com.seatecnologia.gdf.negocia.model.AdvogadoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Advogado service. Represents a row in the &quot;GDF_Advogado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AdvogadoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdvogadoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdvogadoImpl
 * @generated
 */
@JSON(strict = true)
public class AdvogadoModelImpl
	extends BaseModelImpl<Advogado> implements AdvogadoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a advogado model instance should use the <code>Advogado</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_Advogado";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"advogadoId", Types.BIGINT},
		{"qualificacaoId", Types.BIGINT}, {"numeroOab", Types.VARCHAR},
		{"seccional", Types.VARCHAR}, {"carteirinhaOAB", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("advogadoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("qualificacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("numeroOab", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("seccional", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("carteirinhaOAB", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_Advogado (uuid_ VARCHAR(75) null,advogadoId LONG not null primary key,qualificacaoId LONG,numeroOab VARCHAR(255) null,seccional VARCHAR(255) null,carteirinhaOAB LONG)";

	public static final String TABLE_SQL_DROP = "drop table GDF_Advogado";

	public static final String ORDER_BY_JPQL =
		" ORDER BY advogado.advogadoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_Advogado.advogadoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ADVOGADOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AdvogadoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _advogadoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAdvogadoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _advogadoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Advogado.class;
	}

	@Override
	public String getModelClassName() {
		return Advogado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Advogado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Advogado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Advogado, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Advogado)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Advogado, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Advogado, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Advogado)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Advogado, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Advogado, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Advogado, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Advogado, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Advogado, Object>>();

			attributeGetterFunctions.put("uuid", Advogado::getUuid);
			attributeGetterFunctions.put("advogadoId", Advogado::getAdvogadoId);
			attributeGetterFunctions.put(
				"qualificacaoId", Advogado::getQualificacaoId);
			attributeGetterFunctions.put("numeroOab", Advogado::getNumeroOab);
			attributeGetterFunctions.put("seccional", Advogado::getSeccional);
			attributeGetterFunctions.put(
				"carteirinhaOAB", Advogado::getCarteirinhaOAB);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Advogado, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Advogado, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Advogado, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Advogado, String>)Advogado::setUuid);
			attributeSetterBiConsumers.put(
				"advogadoId",
				(BiConsumer<Advogado, Long>)Advogado::setAdvogadoId);
			attributeSetterBiConsumers.put(
				"qualificacaoId",
				(BiConsumer<Advogado, Long>)Advogado::setQualificacaoId);
			attributeSetterBiConsumers.put(
				"numeroOab",
				(BiConsumer<Advogado, String>)Advogado::setNumeroOab);
			attributeSetterBiConsumers.put(
				"seccional",
				(BiConsumer<Advogado, String>)Advogado::setSeccional);
			attributeSetterBiConsumers.put(
				"carteirinhaOAB",
				(BiConsumer<Advogado, Long>)Advogado::setCarteirinhaOAB);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAdvogadoId() {
		return _advogadoId;
	}

	@Override
	public void setAdvogadoId(long advogadoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_advogadoId = advogadoId;
	}

	@JSON
	@Override
	public long getQualificacaoId() {
		return _qualificacaoId;
	}

	@Override
	public void setQualificacaoId(long qualificacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qualificacaoId = qualificacaoId;
	}

	@JSON
	@Override
	public String getNumeroOab() {
		if (_numeroOab == null) {
			return "";
		}
		else {
			return _numeroOab;
		}
	}

	@Override
	public void setNumeroOab(String numeroOab) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numeroOab = numeroOab;
	}

	@JSON
	@Override
	public String getSeccional() {
		if (_seccional == null) {
			return "";
		}
		else {
			return _seccional;
		}
	}

	@Override
	public void setSeccional(String seccional) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seccional = seccional;
	}

	@JSON
	@Override
	public long getCarteirinhaOAB() {
		return _carteirinhaOAB;
	}

	@Override
	public void setCarteirinhaOAB(long carteirinhaOAB) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_carteirinhaOAB = carteirinhaOAB;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Advogado.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Advogado toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Advogado>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AdvogadoImpl advogadoImpl = new AdvogadoImpl();

		advogadoImpl.setUuid(getUuid());
		advogadoImpl.setAdvogadoId(getAdvogadoId());
		advogadoImpl.setQualificacaoId(getQualificacaoId());
		advogadoImpl.setNumeroOab(getNumeroOab());
		advogadoImpl.setSeccional(getSeccional());
		advogadoImpl.setCarteirinhaOAB(getCarteirinhaOAB());

		advogadoImpl.resetOriginalValues();

		return advogadoImpl;
	}

	@Override
	public Advogado cloneWithOriginalValues() {
		AdvogadoImpl advogadoImpl = new AdvogadoImpl();

		advogadoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		advogadoImpl.setAdvogadoId(
			this.<Long>getColumnOriginalValue("advogadoId"));
		advogadoImpl.setQualificacaoId(
			this.<Long>getColumnOriginalValue("qualificacaoId"));
		advogadoImpl.setNumeroOab(
			this.<String>getColumnOriginalValue("numeroOab"));
		advogadoImpl.setSeccional(
			this.<String>getColumnOriginalValue("seccional"));
		advogadoImpl.setCarteirinhaOAB(
			this.<Long>getColumnOriginalValue("carteirinhaOAB"));

		return advogadoImpl;
	}

	@Override
	public int compareTo(Advogado advogado) {
		long primaryKey = advogado.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Advogado)) {
			return false;
		}

		Advogado advogado = (Advogado)object;

		long primaryKey = advogado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Advogado> toCacheModel() {
		AdvogadoCacheModel advogadoCacheModel = new AdvogadoCacheModel();

		advogadoCacheModel.uuid = getUuid();

		String uuid = advogadoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			advogadoCacheModel.uuid = null;
		}

		advogadoCacheModel.advogadoId = getAdvogadoId();

		advogadoCacheModel.qualificacaoId = getQualificacaoId();

		advogadoCacheModel.numeroOab = getNumeroOab();

		String numeroOab = advogadoCacheModel.numeroOab;

		if ((numeroOab != null) && (numeroOab.length() == 0)) {
			advogadoCacheModel.numeroOab = null;
		}

		advogadoCacheModel.seccional = getSeccional();

		String seccional = advogadoCacheModel.seccional;

		if ((seccional != null) && (seccional.length() == 0)) {
			advogadoCacheModel.seccional = null;
		}

		advogadoCacheModel.carteirinhaOAB = getCarteirinhaOAB();

		return advogadoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Advogado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Advogado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Advogado, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Advogado)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Advogado>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Advogado.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _advogadoId;
	private long _qualificacaoId;
	private String _numeroOab;
	private String _seccional;
	private long _carteirinhaOAB;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Advogado, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Advogado)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("advogadoId", _advogadoId);
		_columnOriginalValues.put("qualificacaoId", _qualificacaoId);
		_columnOriginalValues.put("numeroOab", _numeroOab);
		_columnOriginalValues.put("seccional", _seccional);
		_columnOriginalValues.put("carteirinhaOAB", _carteirinhaOAB);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("advogadoId", 2L);

		columnBitmasks.put("qualificacaoId", 4L);

		columnBitmasks.put("numeroOab", 8L);

		columnBitmasks.put("seccional", 16L);

		columnBitmasks.put("carteirinhaOAB", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Advogado _escapedModel;

}