/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.AnexosOutros;
import br.com.seatecnologia.gdf.negocia.model.AnexosOutrosModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AnexosOutros service. Represents a row in the &quot;GDF_AnexosOutros&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnexosOutrosModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnexosOutrosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnexosOutrosImpl
 * @generated
 */
@JSON(strict = true)
public class AnexosOutrosModelImpl
	extends BaseModelImpl<AnexosOutros> implements AnexosOutrosModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a anexos outros model instance should use the <code>AnexosOutros</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_AnexosOutros";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"anexosOutrosId", Types.BIGINT},
		{"dadosRegistroId", Types.BIGINT}, {"outrosAnexo", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anexosOutrosId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dadosRegistroId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("outrosAnexo", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_AnexosOutros (uuid_ VARCHAR(75) null,anexosOutrosId LONG not null primary key,dadosRegistroId LONG,outrosAnexo LONG)";

	public static final String TABLE_SQL_DROP = "drop table GDF_AnexosOutros";

	public static final String ORDER_BY_JPQL =
		" ORDER BY anexosOutros.anexosOutrosId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_AnexosOutros.anexosOutrosId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DADOSREGISTROID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ANEXOSOUTROSID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnexosOutrosModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _anexosOutrosId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnexosOutrosId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _anexosOutrosId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnexosOutros.class;
	}

	@Override
	public String getModelClassName() {
		return AnexosOutros.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnexosOutros, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnexosOutros, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnexosOutros, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnexosOutros)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnexosOutros, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnexosOutros, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnexosOutros)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnexosOutros, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnexosOutros, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AnexosOutros, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AnexosOutros, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<AnexosOutros, Object>>();

			attributeGetterFunctions.put("uuid", AnexosOutros::getUuid);
			attributeGetterFunctions.put(
				"anexosOutrosId", AnexosOutros::getAnexosOutrosId);
			attributeGetterFunctions.put(
				"dadosRegistroId", AnexosOutros::getDadosRegistroId);
			attributeGetterFunctions.put(
				"outrosAnexo", AnexosOutros::getOutrosAnexo);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AnexosOutros, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AnexosOutros, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AnexosOutros, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AnexosOutros, String>)AnexosOutros::setUuid);
			attributeSetterBiConsumers.put(
				"anexosOutrosId",
				(BiConsumer<AnexosOutros, Long>)
					AnexosOutros::setAnexosOutrosId);
			attributeSetterBiConsumers.put(
				"dadosRegistroId",
				(BiConsumer<AnexosOutros, Long>)
					AnexosOutros::setDadosRegistroId);
			attributeSetterBiConsumers.put(
				"outrosAnexo",
				(BiConsumer<AnexosOutros, Long>)AnexosOutros::setOutrosAnexo);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAnexosOutrosId() {
		return _anexosOutrosId;
	}

	@Override
	public void setAnexosOutrosId(long anexosOutrosId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anexosOutrosId = anexosOutrosId;
	}

	@JSON
	@Override
	public long getDadosRegistroId() {
		return _dadosRegistroId;
	}

	@Override
	public void setDadosRegistroId(long dadosRegistroId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dadosRegistroId = dadosRegistroId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDadosRegistroId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("dadosRegistroId"));
	}

	@JSON
	@Override
	public long getOutrosAnexo() {
		return _outrosAnexo;
	}

	@Override
	public void setOutrosAnexo(long outrosAnexo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_outrosAnexo = outrosAnexo;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AnexosOutros.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnexosOutros toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnexosOutros>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnexosOutrosImpl anexosOutrosImpl = new AnexosOutrosImpl();

		anexosOutrosImpl.setUuid(getUuid());
		anexosOutrosImpl.setAnexosOutrosId(getAnexosOutrosId());
		anexosOutrosImpl.setDadosRegistroId(getDadosRegistroId());
		anexosOutrosImpl.setOutrosAnexo(getOutrosAnexo());

		anexosOutrosImpl.resetOriginalValues();

		return anexosOutrosImpl;
	}

	@Override
	public AnexosOutros cloneWithOriginalValues() {
		AnexosOutrosImpl anexosOutrosImpl = new AnexosOutrosImpl();

		anexosOutrosImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		anexosOutrosImpl.setAnexosOutrosId(
			this.<Long>getColumnOriginalValue("anexosOutrosId"));
		anexosOutrosImpl.setDadosRegistroId(
			this.<Long>getColumnOriginalValue("dadosRegistroId"));
		anexosOutrosImpl.setOutrosAnexo(
			this.<Long>getColumnOriginalValue("outrosAnexo"));

		return anexosOutrosImpl;
	}

	@Override
	public int compareTo(AnexosOutros anexosOutros) {
		long primaryKey = anexosOutros.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnexosOutros)) {
			return false;
		}

		AnexosOutros anexosOutros = (AnexosOutros)object;

		long primaryKey = anexosOutros.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnexosOutros> toCacheModel() {
		AnexosOutrosCacheModel anexosOutrosCacheModel =
			new AnexosOutrosCacheModel();

		anexosOutrosCacheModel.uuid = getUuid();

		String uuid = anexosOutrosCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			anexosOutrosCacheModel.uuid = null;
		}

		anexosOutrosCacheModel.anexosOutrosId = getAnexosOutrosId();

		anexosOutrosCacheModel.dadosRegistroId = getDadosRegistroId();

		anexosOutrosCacheModel.outrosAnexo = getOutrosAnexo();

		return anexosOutrosCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnexosOutros, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnexosOutros, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnexosOutros, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AnexosOutros)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnexosOutros>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AnexosOutros.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _anexosOutrosId;
	private long _dadosRegistroId;
	private long _outrosAnexo;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnexosOutros, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnexosOutros)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("anexosOutrosId", _anexosOutrosId);
		_columnOriginalValues.put("dadosRegistroId", _dadosRegistroId);
		_columnOriginalValues.put("outrosAnexo", _outrosAnexo);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("anexosOutrosId", 2L);

		columnBitmasks.put("dadosRegistroId", 4L);

		columnBitmasks.put("outrosAnexo", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnexosOutros _escapedModel;

}