/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.BensDireitosRequerente;
import br.com.seatecnologia.gdf.negocia.model.BensDireitosRequerenteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BensDireitosRequerente service. Represents a row in the &quot;GDF_BensDireitosRequerente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BensDireitosRequerenteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BensDireitosRequerenteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BensDireitosRequerenteImpl
 * @generated
 */
@JSON(strict = true)
public class BensDireitosRequerenteModelImpl
	extends BaseModelImpl<BensDireitosRequerente>
	implements BensDireitosRequerenteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bens direitos requerente model instance should use the <code>BensDireitosRequerente</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_BensDireitosRequerente";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"bemId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"descricao", Types.VARCHAR},
		{"localizacaoDestinacao", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descricao", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("localizacaoDestinacao", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_BensDireitosRequerente (uuid_ VARCHAR(75) null,bemId LONG not null primary key,propostaId LONG,descricao VARCHAR(1000) null,localizacaoDestinacao VARCHAR(1000) null)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_BensDireitosRequerente";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bensDireitosRequerente.bemId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_BensDireitosRequerente.bemId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BEMID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BensDireitosRequerenteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BensDireitosRequerente.class;
	}

	@Override
	public String getModelClassName() {
		return BensDireitosRequerente.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BensDireitosRequerente, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BensDireitosRequerente, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BensDireitosRequerente, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BensDireitosRequerente)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BensDireitosRequerente, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BensDireitosRequerente, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BensDireitosRequerente)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BensDireitosRequerente, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BensDireitosRequerente, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<BensDireitosRequerente, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<BensDireitosRequerente, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BensDireitosRequerente, Object>>();

			attributeGetterFunctions.put(
				"uuid", BensDireitosRequerente::getUuid);
			attributeGetterFunctions.put(
				"bemId", BensDireitosRequerente::getBemId);
			attributeGetterFunctions.put(
				"propostaId", BensDireitosRequerente::getPropostaId);
			attributeGetterFunctions.put(
				"descricao", BensDireitosRequerente::getDescricao);
			attributeGetterFunctions.put(
				"localizacaoDestinacao",
				BensDireitosRequerente::getLocalizacaoDestinacao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<BensDireitosRequerente, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BensDireitosRequerente, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BensDireitosRequerente, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BensDireitosRequerente, String>)
					BensDireitosRequerente::setUuid);
			attributeSetterBiConsumers.put(
				"bemId",
				(BiConsumer<BensDireitosRequerente, Long>)
					BensDireitosRequerente::setBemId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<BensDireitosRequerente, Long>)
					BensDireitosRequerente::setPropostaId);
			attributeSetterBiConsumers.put(
				"descricao",
				(BiConsumer<BensDireitosRequerente, String>)
					BensDireitosRequerente::setDescricao);
			attributeSetterBiConsumers.put(
				"localizacaoDestinacao",
				(BiConsumer<BensDireitosRequerente, String>)
					BensDireitosRequerente::setLocalizacaoDestinacao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBemId() {
		return _bemId;
	}

	@Override
	public void setBemId(long bemId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bemId = bemId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public String getDescricao() {
		if (_descricao == null) {
			return "";
		}
		else {
			return _descricao;
		}
	}

	@Override
	public void setDescricao(String descricao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descricao = descricao;
	}

	@JSON
	@Override
	public String getLocalizacaoDestinacao() {
		if (_localizacaoDestinacao == null) {
			return "";
		}
		else {
			return _localizacaoDestinacao;
		}
	}

	@Override
	public void setLocalizacaoDestinacao(String localizacaoDestinacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_localizacaoDestinacao = localizacaoDestinacao;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BensDireitosRequerente.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BensDireitosRequerente toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BensDireitosRequerente>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BensDireitosRequerenteImpl bensDireitosRequerenteImpl =
			new BensDireitosRequerenteImpl();

		bensDireitosRequerenteImpl.setUuid(getUuid());
		bensDireitosRequerenteImpl.setBemId(getBemId());
		bensDireitosRequerenteImpl.setPropostaId(getPropostaId());
		bensDireitosRequerenteImpl.setDescricao(getDescricao());
		bensDireitosRequerenteImpl.setLocalizacaoDestinacao(
			getLocalizacaoDestinacao());

		bensDireitosRequerenteImpl.resetOriginalValues();

		return bensDireitosRequerenteImpl;
	}

	@Override
	public BensDireitosRequerente cloneWithOriginalValues() {
		BensDireitosRequerenteImpl bensDireitosRequerenteImpl =
			new BensDireitosRequerenteImpl();

		bensDireitosRequerenteImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		bensDireitosRequerenteImpl.setBemId(
			this.<Long>getColumnOriginalValue("bemId"));
		bensDireitosRequerenteImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		bensDireitosRequerenteImpl.setDescricao(
			this.<String>getColumnOriginalValue("descricao"));
		bensDireitosRequerenteImpl.setLocalizacaoDestinacao(
			this.<String>getColumnOriginalValue("localizacaoDestinacao"));

		return bensDireitosRequerenteImpl;
	}

	@Override
	public int compareTo(BensDireitosRequerente bensDireitosRequerente) {
		long primaryKey = bensDireitosRequerente.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BensDireitosRequerente)) {
			return false;
		}

		BensDireitosRequerente bensDireitosRequerente =
			(BensDireitosRequerente)object;

		long primaryKey = bensDireitosRequerente.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BensDireitosRequerente> toCacheModel() {
		BensDireitosRequerenteCacheModel bensDireitosRequerenteCacheModel =
			new BensDireitosRequerenteCacheModel();

		bensDireitosRequerenteCacheModel.uuid = getUuid();

		String uuid = bensDireitosRequerenteCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bensDireitosRequerenteCacheModel.uuid = null;
		}

		bensDireitosRequerenteCacheModel.bemId = getBemId();

		bensDireitosRequerenteCacheModel.propostaId = getPropostaId();

		bensDireitosRequerenteCacheModel.descricao = getDescricao();

		String descricao = bensDireitosRequerenteCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			bensDireitosRequerenteCacheModel.descricao = null;
		}

		bensDireitosRequerenteCacheModel.localizacaoDestinacao =
			getLocalizacaoDestinacao();

		String localizacaoDestinacao =
			bensDireitosRequerenteCacheModel.localizacaoDestinacao;

		if ((localizacaoDestinacao != null) &&
			(localizacaoDestinacao.length() == 0)) {

			bensDireitosRequerenteCacheModel.localizacaoDestinacao = null;
		}

		return bensDireitosRequerenteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BensDireitosRequerente, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BensDireitosRequerente, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BensDireitosRequerente, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BensDireitosRequerente)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BensDireitosRequerente>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BensDireitosRequerente.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _bemId;
	private long _propostaId;
	private String _descricao;
	private String _localizacaoDestinacao;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BensDireitosRequerente, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BensDireitosRequerente)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("bemId", _bemId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("descricao", _descricao);
		_columnOriginalValues.put(
			"localizacaoDestinacao", _localizacaoDestinacao);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("bemId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("descricao", 8L);

		columnBitmasks.put("localizacaoDestinacao", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BensDireitosRequerente _escapedModel;

}