/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.ConcessaoDf;
import br.com.seatecnologia.gdf.negocia.model.ConcessaoDfModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ConcessaoDf service. Represents a row in the &quot;GDF_ConcessaoDf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConcessaoDfModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConcessaoDfImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConcessaoDfImpl
 * @generated
 */
@JSON(strict = true)
public class ConcessaoDfModelImpl
	extends BaseModelImpl<ConcessaoDf> implements ConcessaoDfModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a concessao df model instance should use the <code>ConcessaoDf</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_ConcessaoDf";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"concessaoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"percentualDescontoJuros", Types.DOUBLE},
		{"percentualDescontoPrincipal", Types.DOUBLE},
		{"observacoes", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("concessaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("percentualDescontoJuros", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("percentualDescontoPrincipal", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("observacoes", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_ConcessaoDf (uuid_ VARCHAR(75) null,concessaoId LONG not null primary key,propostaId LONG,percentualDescontoJuros DOUBLE,percentualDescontoPrincipal DOUBLE,observacoes VARCHAR(255) null)";

	public static final String TABLE_SQL_DROP = "drop table GDF_ConcessaoDf";

	public static final String ORDER_BY_JPQL =
		" ORDER BY concessaoDf.concessaoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_ConcessaoDf.concessaoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONCESSAOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ConcessaoDfModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _concessaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConcessaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _concessaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConcessaoDf.class;
	}

	@Override
	public String getModelClassName() {
		return ConcessaoDf.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConcessaoDf, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConcessaoDf, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcessaoDf, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConcessaoDf)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConcessaoDf, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConcessaoDf, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConcessaoDf)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConcessaoDf, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConcessaoDf, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ConcessaoDf, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ConcessaoDf, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<ConcessaoDf, Object>>();

			attributeGetterFunctions.put("uuid", ConcessaoDf::getUuid);
			attributeGetterFunctions.put(
				"concessaoId", ConcessaoDf::getConcessaoId);
			attributeGetterFunctions.put(
				"propostaId", ConcessaoDf::getPropostaId);
			attributeGetterFunctions.put(
				"percentualDescontoJuros",
				ConcessaoDf::getPercentualDescontoJuros);
			attributeGetterFunctions.put(
				"percentualDescontoPrincipal",
				ConcessaoDf::getPercentualDescontoPrincipal);
			attributeGetterFunctions.put(
				"observacoes", ConcessaoDf::getObservacoes);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ConcessaoDf, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ConcessaoDf, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ConcessaoDf, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<ConcessaoDf, String>)ConcessaoDf::setUuid);
			attributeSetterBiConsumers.put(
				"concessaoId",
				(BiConsumer<ConcessaoDf, Long>)ConcessaoDf::setConcessaoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<ConcessaoDf, Long>)ConcessaoDf::setPropostaId);
			attributeSetterBiConsumers.put(
				"percentualDescontoJuros",
				(BiConsumer<ConcessaoDf, Double>)
					ConcessaoDf::setPercentualDescontoJuros);
			attributeSetterBiConsumers.put(
				"percentualDescontoPrincipal",
				(BiConsumer<ConcessaoDf, Double>)
					ConcessaoDf::setPercentualDescontoPrincipal);
			attributeSetterBiConsumers.put(
				"observacoes",
				(BiConsumer<ConcessaoDf, String>)ConcessaoDf::setObservacoes);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getConcessaoId() {
		return _concessaoId;
	}

	@Override
	public void setConcessaoId(long concessaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_concessaoId = concessaoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public double getPercentualDescontoJuros() {
		return _percentualDescontoJuros;
	}

	@Override
	public void setPercentualDescontoJuros(double percentualDescontoJuros) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_percentualDescontoJuros = percentualDescontoJuros;
	}

	@JSON
	@Override
	public double getPercentualDescontoPrincipal() {
		return _percentualDescontoPrincipal;
	}

	@Override
	public void setPercentualDescontoPrincipal(
		double percentualDescontoPrincipal) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_percentualDescontoPrincipal = percentualDescontoPrincipal;
	}

	@JSON
	@Override
	public String getObservacoes() {
		if (_observacoes == null) {
			return "";
		}
		else {
			return _observacoes;
		}
	}

	@Override
	public void setObservacoes(String observacoes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_observacoes = observacoes;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ConcessaoDf.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConcessaoDf toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ConcessaoDf>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConcessaoDfImpl concessaoDfImpl = new ConcessaoDfImpl();

		concessaoDfImpl.setUuid(getUuid());
		concessaoDfImpl.setConcessaoId(getConcessaoId());
		concessaoDfImpl.setPropostaId(getPropostaId());
		concessaoDfImpl.setPercentualDescontoJuros(
			getPercentualDescontoJuros());
		concessaoDfImpl.setPercentualDescontoPrincipal(
			getPercentualDescontoPrincipal());
		concessaoDfImpl.setObservacoes(getObservacoes());

		concessaoDfImpl.resetOriginalValues();

		return concessaoDfImpl;
	}

	@Override
	public ConcessaoDf cloneWithOriginalValues() {
		ConcessaoDfImpl concessaoDfImpl = new ConcessaoDfImpl();

		concessaoDfImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		concessaoDfImpl.setConcessaoId(
			this.<Long>getColumnOriginalValue("concessaoId"));
		concessaoDfImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		concessaoDfImpl.setPercentualDescontoJuros(
			this.<Double>getColumnOriginalValue("percentualDescontoJuros"));
		concessaoDfImpl.setPercentualDescontoPrincipal(
			this.<Double>getColumnOriginalValue("percentualDescontoPrincipal"));
		concessaoDfImpl.setObservacoes(
			this.<String>getColumnOriginalValue("observacoes"));

		return concessaoDfImpl;
	}

	@Override
	public int compareTo(ConcessaoDf concessaoDf) {
		long primaryKey = concessaoDf.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ConcessaoDf)) {
			return false;
		}

		ConcessaoDf concessaoDf = (ConcessaoDf)object;

		long primaryKey = concessaoDf.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ConcessaoDf> toCacheModel() {
		ConcessaoDfCacheModel concessaoDfCacheModel =
			new ConcessaoDfCacheModel();

		concessaoDfCacheModel.uuid = getUuid();

		String uuid = concessaoDfCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			concessaoDfCacheModel.uuid = null;
		}

		concessaoDfCacheModel.concessaoId = getConcessaoId();

		concessaoDfCacheModel.propostaId = getPropostaId();

		concessaoDfCacheModel.percentualDescontoJuros =
			getPercentualDescontoJuros();

		concessaoDfCacheModel.percentualDescontoPrincipal =
			getPercentualDescontoPrincipal();

		concessaoDfCacheModel.observacoes = getObservacoes();

		String observacoes = concessaoDfCacheModel.observacoes;

		if ((observacoes != null) && (observacoes.length() == 0)) {
			concessaoDfCacheModel.observacoes = null;
		}

		return concessaoDfCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConcessaoDf, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConcessaoDf, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConcessaoDf, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ConcessaoDf)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ConcessaoDf>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ConcessaoDf.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _concessaoId;
	private long _propostaId;
	private double _percentualDescontoJuros;
	private double _percentualDescontoPrincipal;
	private String _observacoes;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ConcessaoDf, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ConcessaoDf)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("concessaoId", _concessaoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put(
			"percentualDescontoJuros", _percentualDescontoJuros);
		_columnOriginalValues.put(
			"percentualDescontoPrincipal", _percentualDescontoPrincipal);
		_columnOriginalValues.put("observacoes", _observacoes);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("concessaoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("percentualDescontoJuros", 8L);

		columnBitmasks.put("percentualDescontoPrincipal", 16L);

		columnBitmasks.put("observacoes", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ConcessaoDf _escapedModel;

}