/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.CreditoTransacionado;
import br.com.seatecnologia.gdf.negocia.service.CreditoTransacionadoLocalServiceUtil;

/**
 * The extended model base implementation for the CreditoTransacionado service. Represents a row in the &quot;GDF_CreditoTransacionado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CreditoTransacionadoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreditoTransacionadoImpl
 * @see CreditoTransacionado
 * @generated
 */
public abstract class CreditoTransacionadoBaseImpl
	extends CreditoTransacionadoModelImpl implements CreditoTransacionado {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a credito transacionado model instance should use the <code>CreditoTransacionado</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CreditoTransacionadoLocalServiceUtil.addCreditoTransacionado(this);
		}
		else {
			CreditoTransacionadoLocalServiceUtil.updateCreditoTransacionado(
				this);
		}
	}

}