/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.CredorProposta;
import br.com.seatecnologia.gdf.negocia.service.CredorPropostaLocalServiceUtil;

/**
 * The extended model base implementation for the CredorProposta service. Represents a row in the &quot;GDF_CredorProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CredorPropostaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CredorPropostaImpl
 * @see CredorProposta
 * @generated
 */
public abstract class CredorPropostaBaseImpl
	extends CredorPropostaModelImpl implements CredorProposta {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a credor proposta model instance should use the <code>CredorProposta</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CredorPropostaLocalServiceUtil.addCredorProposta(this);
		}
		else {
			CredorPropostaLocalServiceUtil.updateCredorProposta(this);
		}
	}

}