/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.CredorProposta;
import br.com.seatecnologia.gdf.negocia.model.CredorPropostaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CredorProposta service. Represents a row in the &quot;GDF_CredorProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CredorPropostaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CredorPropostaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CredorPropostaImpl
 * @generated
 */
@JSON(strict = true)
public class CredorPropostaModelImpl
	extends BaseModelImpl<CredorProposta> implements CredorPropostaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a credor proposta model instance should use the <code>CredorProposta</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_CredorProposta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"credorPropostaId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"credorId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("credorPropostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("credorId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_CredorProposta (uuid_ VARCHAR(75) null,credorPropostaId LONG not null primary key,propostaId LONG,credorId LONG)";

	public static final String TABLE_SQL_DROP = "drop table GDF_CredorProposta";

	public static final String ORDER_BY_JPQL =
		" ORDER BY credorProposta.credorPropostaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_CredorProposta.credorPropostaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREDORPROPOSTAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CredorPropostaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _credorPropostaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCredorPropostaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _credorPropostaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CredorProposta.class;
	}

	@Override
	public String getModelClassName() {
		return CredorProposta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CredorProposta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CredorProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CredorProposta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CredorProposta)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CredorProposta, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CredorProposta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CredorProposta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CredorProposta, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CredorProposta, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CredorProposta, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CredorProposta, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CredorProposta, Object>>();

			attributeGetterFunctions.put("uuid", CredorProposta::getUuid);
			attributeGetterFunctions.put(
				"credorPropostaId", CredorProposta::getCredorPropostaId);
			attributeGetterFunctions.put(
				"propostaId", CredorProposta::getPropostaId);
			attributeGetterFunctions.put(
				"credorId", CredorProposta::getCredorId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CredorProposta, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CredorProposta, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<CredorProposta, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CredorProposta, String>)CredorProposta::setUuid);
			attributeSetterBiConsumers.put(
				"credorPropostaId",
				(BiConsumer<CredorProposta, Long>)
					CredorProposta::setCredorPropostaId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<CredorProposta, Long>)
					CredorProposta::setPropostaId);
			attributeSetterBiConsumers.put(
				"credorId",
				(BiConsumer<CredorProposta, Long>)CredorProposta::setCredorId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCredorPropostaId() {
		return _credorPropostaId;
	}

	@Override
	public void setCredorPropostaId(long credorPropostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_credorPropostaId = credorPropostaId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public long getCredorId() {
		return _credorId;
	}

	@Override
	public void setCredorId(long credorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_credorId = credorId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CredorProposta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CredorProposta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CredorProposta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CredorPropostaImpl credorPropostaImpl = new CredorPropostaImpl();

		credorPropostaImpl.setUuid(getUuid());
		credorPropostaImpl.setCredorPropostaId(getCredorPropostaId());
		credorPropostaImpl.setPropostaId(getPropostaId());
		credorPropostaImpl.setCredorId(getCredorId());

		credorPropostaImpl.resetOriginalValues();

		return credorPropostaImpl;
	}

	@Override
	public CredorProposta cloneWithOriginalValues() {
		CredorPropostaImpl credorPropostaImpl = new CredorPropostaImpl();

		credorPropostaImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		credorPropostaImpl.setCredorPropostaId(
			this.<Long>getColumnOriginalValue("credorPropostaId"));
		credorPropostaImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		credorPropostaImpl.setCredorId(
			this.<Long>getColumnOriginalValue("credorId"));

		return credorPropostaImpl;
	}

	@Override
	public int compareTo(CredorProposta credorProposta) {
		long primaryKey = credorProposta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CredorProposta)) {
			return false;
		}

		CredorProposta credorProposta = (CredorProposta)object;

		long primaryKey = credorProposta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CredorProposta> toCacheModel() {
		CredorPropostaCacheModel credorPropostaCacheModel =
			new CredorPropostaCacheModel();

		credorPropostaCacheModel.uuid = getUuid();

		String uuid = credorPropostaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			credorPropostaCacheModel.uuid = null;
		}

		credorPropostaCacheModel.credorPropostaId = getCredorPropostaId();

		credorPropostaCacheModel.propostaId = getPropostaId();

		credorPropostaCacheModel.credorId = getCredorId();

		return credorPropostaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CredorProposta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CredorProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CredorProposta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CredorProposta)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CredorProposta>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CredorProposta.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _credorPropostaId;
	private long _propostaId;
	private long _credorId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CredorProposta, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CredorProposta)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("credorPropostaId", _credorPropostaId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("credorId", _credorId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("credorPropostaId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("credorId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CredorProposta _escapedModel;

}