/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.DadosContribuinte;
import br.com.seatecnologia.gdf.negocia.model.DadosContribuinteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DadosContribuinte service. Represents a row in the &quot;GDF_DadosContribuinte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DadosContribuinteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DadosContribuinteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DadosContribuinteImpl
 * @generated
 */
@JSON(strict = true)
public class DadosContribuinteModelImpl
	extends BaseModelImpl<DadosContribuinte> implements DadosContribuinteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dados contribuinte model instance should use the <code>DadosContribuinte</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_DadosContribuinte";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"dadosContribuinteId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"userId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"qualificacaoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dadosContribuinteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("qualificacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_DadosContribuinte (uuid_ VARCHAR(75) null,dadosContribuinteId LONG not null primary key,createDate DATE null,modifiedDate DATE null,userId LONG,groupId LONG,companyId LONG,qualificacaoId LONG,propostaId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_DadosContribuinte";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dadosContribuinte.dadosContribuinteId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_DadosContribuinte.dadosContribuinteId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DADOSCONTRIBUINTEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DadosContribuinteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dadosContribuinteId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDadosContribuinteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dadosContribuinteId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DadosContribuinte.class;
	}

	@Override
	public String getModelClassName() {
		return DadosContribuinte.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DadosContribuinte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DadosContribuinte, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DadosContribuinte, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DadosContribuinte)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DadosContribuinte, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DadosContribuinte, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DadosContribuinte)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DadosContribuinte, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DadosContribuinte, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DadosContribuinte, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DadosContribuinte, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DadosContribuinte, Object>>();

			attributeGetterFunctions.put("uuid", DadosContribuinte::getUuid);
			attributeGetterFunctions.put(
				"dadosContribuinteId",
				DadosContribuinte::getDadosContribuinteId);
			attributeGetterFunctions.put(
				"createDate", DadosContribuinte::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", DadosContribuinte::getModifiedDate);
			attributeGetterFunctions.put(
				"userId", DadosContribuinte::getUserId);
			attributeGetterFunctions.put(
				"groupId", DadosContribuinte::getGroupId);
			attributeGetterFunctions.put(
				"companyId", DadosContribuinte::getCompanyId);
			attributeGetterFunctions.put(
				"qualificacaoId", DadosContribuinte::getQualificacaoId);
			attributeGetterFunctions.put(
				"propostaId", DadosContribuinte::getPropostaId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DadosContribuinte, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DadosContribuinte, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DadosContribuinte, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<DadosContribuinte, String>)
					DadosContribuinte::setUuid);
			attributeSetterBiConsumers.put(
				"dadosContribuinteId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setDadosContribuinteId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<DadosContribuinte, Date>)
					DadosContribuinte::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<DadosContribuinte, Date>)
					DadosContribuinte::setModifiedDate);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setUserId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setCompanyId);
			attributeSetterBiConsumers.put(
				"qualificacaoId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setQualificacaoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<DadosContribuinte, Long>)
					DadosContribuinte::setPropostaId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDadosContribuinteId() {
		return _dadosContribuinteId;
	}

	@Override
	public void setDadosContribuinteId(long dadosContribuinteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dadosContribuinteId = dadosContribuinteId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getQualificacaoId() {
		return _qualificacaoId;
	}

	@Override
	public void setQualificacaoId(long qualificacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qualificacaoId = qualificacaoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DadosContribuinte.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DadosContribuinte.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DadosContribuinte toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DadosContribuinte>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DadosContribuinteImpl dadosContribuinteImpl =
			new DadosContribuinteImpl();

		dadosContribuinteImpl.setUuid(getUuid());
		dadosContribuinteImpl.setDadosContribuinteId(getDadosContribuinteId());
		dadosContribuinteImpl.setCreateDate(getCreateDate());
		dadosContribuinteImpl.setModifiedDate(getModifiedDate());
		dadosContribuinteImpl.setUserId(getUserId());
		dadosContribuinteImpl.setGroupId(getGroupId());
		dadosContribuinteImpl.setCompanyId(getCompanyId());
		dadosContribuinteImpl.setQualificacaoId(getQualificacaoId());
		dadosContribuinteImpl.setPropostaId(getPropostaId());

		dadosContribuinteImpl.resetOriginalValues();

		return dadosContribuinteImpl;
	}

	@Override
	public DadosContribuinte cloneWithOriginalValues() {
		DadosContribuinteImpl dadosContribuinteImpl =
			new DadosContribuinteImpl();

		dadosContribuinteImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		dadosContribuinteImpl.setDadosContribuinteId(
			this.<Long>getColumnOriginalValue("dadosContribuinteId"));
		dadosContribuinteImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dadosContribuinteImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dadosContribuinteImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		dadosContribuinteImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		dadosContribuinteImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		dadosContribuinteImpl.setQualificacaoId(
			this.<Long>getColumnOriginalValue("qualificacaoId"));
		dadosContribuinteImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));

		return dadosContribuinteImpl;
	}

	@Override
	public int compareTo(DadosContribuinte dadosContribuinte) {
		long primaryKey = dadosContribuinte.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DadosContribuinte)) {
			return false;
		}

		DadosContribuinte dadosContribuinte = (DadosContribuinte)object;

		long primaryKey = dadosContribuinte.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DadosContribuinte> toCacheModel() {
		DadosContribuinteCacheModel dadosContribuinteCacheModel =
			new DadosContribuinteCacheModel();

		dadosContribuinteCacheModel.uuid = getUuid();

		String uuid = dadosContribuinteCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dadosContribuinteCacheModel.uuid = null;
		}

		dadosContribuinteCacheModel.dadosContribuinteId =
			getDadosContribuinteId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			dadosContribuinteCacheModel.createDate = createDate.getTime();
		}
		else {
			dadosContribuinteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dadosContribuinteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dadosContribuinteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dadosContribuinteCacheModel.userId = getUserId();

		dadosContribuinteCacheModel.groupId = getGroupId();

		dadosContribuinteCacheModel.companyId = getCompanyId();

		dadosContribuinteCacheModel.qualificacaoId = getQualificacaoId();

		dadosContribuinteCacheModel.propostaId = getPropostaId();

		return dadosContribuinteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DadosContribuinte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DadosContribuinte, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DadosContribuinte, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DadosContribuinte)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DadosContribuinte>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DadosContribuinte.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _dadosContribuinteId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _userId;
	private long _groupId;
	private long _companyId;
	private long _qualificacaoId;
	private long _propostaId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DadosContribuinte, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DadosContribuinte)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("dadosContribuinteId", _dadosContribuinteId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("qualificacaoId", _qualificacaoId);
		_columnOriginalValues.put("propostaId", _propostaId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("dadosContribuinteId", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("modifiedDate", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("qualificacaoId", 128L);

		columnBitmasks.put("propostaId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DadosContribuinte _escapedModel;

}