/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Declaracao;
import br.com.seatecnologia.gdf.negocia.service.DeclaracaoLocalServiceUtil;

/**
 * The extended model base implementation for the Declaracao service. Represents a row in the &quot;GDF_Declaracao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeclaracaoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DeclaracaoImpl
 * @see Declaracao
 * @generated
 */
public abstract class DeclaracaoBaseImpl
	extends DeclaracaoModelImpl implements Declaracao {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a declaracao model instance should use the <code>Declaracao</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DeclaracaoLocalServiceUtil.addDeclaracao(this);
		}
		else {
			DeclaracaoLocalServiceUtil.updateDeclaracao(this);
		}
	}

}