/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.DemonstracaoContabil;
import br.com.seatecnologia.gdf.negocia.model.DemonstracaoContabilModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DemonstracaoContabil service. Represents a row in the &quot;GDF_DemonstracaoContabil&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DemonstracaoContabilModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DemonstracaoContabilImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DemonstracaoContabilImpl
 * @generated
 */
@JSON(strict = true)
public class DemonstracaoContabilModelImpl
	extends BaseModelImpl<DemonstracaoContabil>
	implements DemonstracaoContabilModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a demonstracao contabil model instance should use the <code>DemonstracaoContabil</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_DemonstracaoContabil";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"demonstracaoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"fileEntryId", Types.BIGINT},
		{"tipoDocumento", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("demonstracaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipoDocumento", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_DemonstracaoContabil (uuid_ VARCHAR(75) null,demonstracaoId LONG not null primary key,propostaId LONG,fileEntryId LONG,tipoDocumento INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_DemonstracaoContabil";

	public static final String ORDER_BY_JPQL =
		" ORDER BY demonstracaoContabil.demonstracaoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_DemonstracaoContabil.demonstracaoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEMONSTRACAOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DemonstracaoContabilModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _demonstracaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDemonstracaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _demonstracaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DemonstracaoContabil.class;
	}

	@Override
	public String getModelClassName() {
		return DemonstracaoContabil.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DemonstracaoContabil, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DemonstracaoContabil, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DemonstracaoContabil, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DemonstracaoContabil)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DemonstracaoContabil, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DemonstracaoContabil, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DemonstracaoContabil)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DemonstracaoContabil, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DemonstracaoContabil, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DemonstracaoContabil, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DemonstracaoContabil, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DemonstracaoContabil, Object>>();

			attributeGetterFunctions.put("uuid", DemonstracaoContabil::getUuid);
			attributeGetterFunctions.put(
				"demonstracaoId", DemonstracaoContabil::getDemonstracaoId);
			attributeGetterFunctions.put(
				"propostaId", DemonstracaoContabil::getPropostaId);
			attributeGetterFunctions.put(
				"fileEntryId", DemonstracaoContabil::getFileEntryId);
			attributeGetterFunctions.put(
				"tipoDocumento", DemonstracaoContabil::getTipoDocumento);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<DemonstracaoContabil, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DemonstracaoContabil, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DemonstracaoContabil, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<DemonstracaoContabil, String>)
					DemonstracaoContabil::setUuid);
			attributeSetterBiConsumers.put(
				"demonstracaoId",
				(BiConsumer<DemonstracaoContabil, Long>)
					DemonstracaoContabil::setDemonstracaoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<DemonstracaoContabil, Long>)
					DemonstracaoContabil::setPropostaId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<DemonstracaoContabil, Long>)
					DemonstracaoContabil::setFileEntryId);
			attributeSetterBiConsumers.put(
				"tipoDocumento",
				(BiConsumer<DemonstracaoContabil, Integer>)
					DemonstracaoContabil::setTipoDocumento);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getDemonstracaoId() {
		return _demonstracaoId;
	}

	@Override
	public void setDemonstracaoId(long demonstracaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_demonstracaoId = demonstracaoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public int getTipoDocumento() {
		return _tipoDocumento;
	}

	@Override
	public void setTipoDocumento(int tipoDocumento) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipoDocumento = tipoDocumento;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DemonstracaoContabil.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DemonstracaoContabil toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DemonstracaoContabil>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DemonstracaoContabilImpl demonstracaoContabilImpl =
			new DemonstracaoContabilImpl();

		demonstracaoContabilImpl.setUuid(getUuid());
		demonstracaoContabilImpl.setDemonstracaoId(getDemonstracaoId());
		demonstracaoContabilImpl.setPropostaId(getPropostaId());
		demonstracaoContabilImpl.setFileEntryId(getFileEntryId());
		demonstracaoContabilImpl.setTipoDocumento(getTipoDocumento());

		demonstracaoContabilImpl.resetOriginalValues();

		return demonstracaoContabilImpl;
	}

	@Override
	public DemonstracaoContabil cloneWithOriginalValues() {
		DemonstracaoContabilImpl demonstracaoContabilImpl =
			new DemonstracaoContabilImpl();

		demonstracaoContabilImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		demonstracaoContabilImpl.setDemonstracaoId(
			this.<Long>getColumnOriginalValue("demonstracaoId"));
		demonstracaoContabilImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		demonstracaoContabilImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		demonstracaoContabilImpl.setTipoDocumento(
			this.<Integer>getColumnOriginalValue("tipoDocumento"));

		return demonstracaoContabilImpl;
	}

	@Override
	public int compareTo(DemonstracaoContabil demonstracaoContabil) {
		long primaryKey = demonstracaoContabil.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DemonstracaoContabil)) {
			return false;
		}

		DemonstracaoContabil demonstracaoContabil =
			(DemonstracaoContabil)object;

		long primaryKey = demonstracaoContabil.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DemonstracaoContabil> toCacheModel() {
		DemonstracaoContabilCacheModel demonstracaoContabilCacheModel =
			new DemonstracaoContabilCacheModel();

		demonstracaoContabilCacheModel.uuid = getUuid();

		String uuid = demonstracaoContabilCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			demonstracaoContabilCacheModel.uuid = null;
		}

		demonstracaoContabilCacheModel.demonstracaoId = getDemonstracaoId();

		demonstracaoContabilCacheModel.propostaId = getPropostaId();

		demonstracaoContabilCacheModel.fileEntryId = getFileEntryId();

		demonstracaoContabilCacheModel.tipoDocumento = getTipoDocumento();

		return demonstracaoContabilCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DemonstracaoContabil, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DemonstracaoContabil, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DemonstracaoContabil, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DemonstracaoContabil)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DemonstracaoContabil>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DemonstracaoContabil.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _demonstracaoId;
	private long _propostaId;
	private long _fileEntryId;
	private int _tipoDocumento;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DemonstracaoContabil, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DemonstracaoContabil)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("demonstracaoId", _demonstracaoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("tipoDocumento", _tipoDocumento);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("demonstracaoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("fileEntryId", 8L);

		columnBitmasks.put("tipoDocumento", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DemonstracaoContabil _escapedModel;

}