/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Edital;
import br.com.seatecnologia.gdf.negocia.service.EditalLocalServiceUtil;

/**
 * The extended model base implementation for the Edital service. Represents a row in the &quot;GDF_Edital&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EditalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EditalImpl
 * @see Edital
 * @generated
 */
public abstract class EditalBaseImpl extends EditalModelImpl implements Edital {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edital model instance should use the <code>Edital</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EditalLocalServiceUtil.addEdital(this);
		}
		else {
			EditalLocalServiceUtil.updateEdital(this);
		}
	}

}