/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Encargo;
import br.com.seatecnologia.gdf.negocia.model.EncargoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Encargo service. Represents a row in the &quot;GDF_Encargo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EncargoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EncargoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EncargoImpl
 * @generated
 */
@JSON(strict = true)
public class EncargoModelImpl
	extends BaseModelImpl<Encargo> implements EncargoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a encargo model instance should use the <code>Encargo</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_Encargo";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"encargoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"valorEncargos", Types.DOUBLE},
		{"descricaoEncargos", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("encargoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("valorEncargos", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("descricaoEncargos", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_Encargo (uuid_ VARCHAR(75) null,encargoId LONG not null primary key,propostaId LONG,valorEncargos DOUBLE,descricaoEncargos VARCHAR(255) null)";

	public static final String TABLE_SQL_DROP = "drop table GDF_Encargo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY encargo.encargoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_Encargo.encargoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENCARGOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EncargoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _encargoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEncargoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _encargoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Encargo.class;
	}

	@Override
	public String getModelClassName() {
		return Encargo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Encargo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Encargo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Encargo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Encargo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Encargo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Encargo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Encargo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Encargo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Encargo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Encargo, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Encargo, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Encargo, Object>>();

			attributeGetterFunctions.put("uuid", Encargo::getUuid);
			attributeGetterFunctions.put("encargoId", Encargo::getEncargoId);
			attributeGetterFunctions.put("propostaId", Encargo::getPropostaId);
			attributeGetterFunctions.put(
				"valorEncargos", Encargo::getValorEncargos);
			attributeGetterFunctions.put(
				"descricaoEncargos", Encargo::getDescricaoEncargos);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Encargo, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Encargo, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Encargo, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Encargo, String>)Encargo::setUuid);
			attributeSetterBiConsumers.put(
				"encargoId", (BiConsumer<Encargo, Long>)Encargo::setEncargoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<Encargo, Long>)Encargo::setPropostaId);
			attributeSetterBiConsumers.put(
				"valorEncargos",
				(BiConsumer<Encargo, Double>)Encargo::setValorEncargos);
			attributeSetterBiConsumers.put(
				"descricaoEncargos",
				(BiConsumer<Encargo, String>)Encargo::setDescricaoEncargos);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEncargoId() {
		return _encargoId;
	}

	@Override
	public void setEncargoId(long encargoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_encargoId = encargoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public double getValorEncargos() {
		return _valorEncargos;
	}

	@Override
	public void setValorEncargos(double valorEncargos) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valorEncargos = valorEncargos;
	}

	@JSON
	@Override
	public String getDescricaoEncargos() {
		if (_descricaoEncargos == null) {
			return "";
		}
		else {
			return _descricaoEncargos;
		}
	}

	@Override
	public void setDescricaoEncargos(String descricaoEncargos) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descricaoEncargos = descricaoEncargos;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Encargo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Encargo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Encargo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EncargoImpl encargoImpl = new EncargoImpl();

		encargoImpl.setUuid(getUuid());
		encargoImpl.setEncargoId(getEncargoId());
		encargoImpl.setPropostaId(getPropostaId());
		encargoImpl.setValorEncargos(getValorEncargos());
		encargoImpl.setDescricaoEncargos(getDescricaoEncargos());

		encargoImpl.resetOriginalValues();

		return encargoImpl;
	}

	@Override
	public Encargo cloneWithOriginalValues() {
		EncargoImpl encargoImpl = new EncargoImpl();

		encargoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		encargoImpl.setEncargoId(
			this.<Long>getColumnOriginalValue("encargoId"));
		encargoImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		encargoImpl.setValorEncargos(
			this.<Double>getColumnOriginalValue("valorEncargos"));
		encargoImpl.setDescricaoEncargos(
			this.<String>getColumnOriginalValue("descricaoEncargos"));

		return encargoImpl;
	}

	@Override
	public int compareTo(Encargo encargo) {
		long primaryKey = encargo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Encargo)) {
			return false;
		}

		Encargo encargo = (Encargo)object;

		long primaryKey = encargo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Encargo> toCacheModel() {
		EncargoCacheModel encargoCacheModel = new EncargoCacheModel();

		encargoCacheModel.uuid = getUuid();

		String uuid = encargoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			encargoCacheModel.uuid = null;
		}

		encargoCacheModel.encargoId = getEncargoId();

		encargoCacheModel.propostaId = getPropostaId();

		encargoCacheModel.valorEncargos = getValorEncargos();

		encargoCacheModel.descricaoEncargos = getDescricaoEncargos();

		String descricaoEncargos = encargoCacheModel.descricaoEncargos;

		if ((descricaoEncargos != null) && (descricaoEncargos.length() == 0)) {
			encargoCacheModel.descricaoEncargos = null;
		}

		return encargoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Encargo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Encargo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Encargo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Encargo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Encargo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Encargo.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _encargoId;
	private long _propostaId;
	private double _valorEncargos;
	private String _descricaoEncargos;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Encargo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Encargo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("encargoId", _encargoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("valorEncargos", _valorEncargos);
		_columnOriginalValues.put("descricaoEncargos", _descricaoEncargos);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("encargoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("valorEncargos", 8L);

		columnBitmasks.put("descricaoEncargos", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Encargo _escapedModel;

}