/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.FundamentacaoPedido;
import br.com.seatecnologia.gdf.negocia.model.FundamentacaoPedidoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FundamentacaoPedido service. Represents a row in the &quot;GDF_FundamentacaoPedido&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FundamentacaoPedidoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FundamentacaoPedidoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FundamentacaoPedidoImpl
 * @generated
 */
@JSON(strict = true)
public class FundamentacaoPedidoModelImpl
	extends BaseModelImpl<FundamentacaoPedido>
	implements FundamentacaoPedidoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fundamentacao pedido model instance should use the <code>FundamentacaoPedido</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_FundamentacaoPedido";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"fundamentacaoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"fundamentacaoPedido", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fundamentacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fundamentacaoPedido", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_FundamentacaoPedido (uuid_ VARCHAR(75) null,fundamentacaoId LONG not null primary key,propostaId LONG,fundamentacaoPedido TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_FundamentacaoPedido";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fundamentacaoPedido.fundamentacaoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_FundamentacaoPedido.fundamentacaoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FUNDAMENTACAOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FundamentacaoPedidoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fundamentacaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFundamentacaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fundamentacaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FundamentacaoPedido.class;
	}

	@Override
	public String getModelClassName() {
		return FundamentacaoPedido.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FundamentacaoPedido, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FundamentacaoPedido, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FundamentacaoPedido, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FundamentacaoPedido)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FundamentacaoPedido, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FundamentacaoPedido, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FundamentacaoPedido)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FundamentacaoPedido, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FundamentacaoPedido, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FundamentacaoPedido, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FundamentacaoPedido, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<FundamentacaoPedido, Object>>();

			attributeGetterFunctions.put("uuid", FundamentacaoPedido::getUuid);
			attributeGetterFunctions.put(
				"fundamentacaoId", FundamentacaoPedido::getFundamentacaoId);
			attributeGetterFunctions.put(
				"propostaId", FundamentacaoPedido::getPropostaId);
			attributeGetterFunctions.put(
				"fundamentacaoPedido",
				FundamentacaoPedido::getFundamentacaoPedido);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<FundamentacaoPedido, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FundamentacaoPedido, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<FundamentacaoPedido, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<FundamentacaoPedido, String>)
					FundamentacaoPedido::setUuid);
			attributeSetterBiConsumers.put(
				"fundamentacaoId",
				(BiConsumer<FundamentacaoPedido, Long>)
					FundamentacaoPedido::setFundamentacaoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<FundamentacaoPedido, Long>)
					FundamentacaoPedido::setPropostaId);
			attributeSetterBiConsumers.put(
				"fundamentacaoPedido",
				(BiConsumer<FundamentacaoPedido, String>)
					FundamentacaoPedido::setFundamentacaoPedido);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFundamentacaoId() {
		return _fundamentacaoId;
	}

	@Override
	public void setFundamentacaoId(long fundamentacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fundamentacaoId = fundamentacaoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public String getFundamentacaoPedido() {
		if (_fundamentacaoPedido == null) {
			return "";
		}
		else {
			return _fundamentacaoPedido;
		}
	}

	@Override
	public void setFundamentacaoPedido(String fundamentacaoPedido) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fundamentacaoPedido = fundamentacaoPedido;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FundamentacaoPedido.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FundamentacaoPedido toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FundamentacaoPedido>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FundamentacaoPedidoImpl fundamentacaoPedidoImpl =
			new FundamentacaoPedidoImpl();

		fundamentacaoPedidoImpl.setUuid(getUuid());
		fundamentacaoPedidoImpl.setFundamentacaoId(getFundamentacaoId());
		fundamentacaoPedidoImpl.setPropostaId(getPropostaId());
		fundamentacaoPedidoImpl.setFundamentacaoPedido(
			getFundamentacaoPedido());

		fundamentacaoPedidoImpl.resetOriginalValues();

		return fundamentacaoPedidoImpl;
	}

	@Override
	public FundamentacaoPedido cloneWithOriginalValues() {
		FundamentacaoPedidoImpl fundamentacaoPedidoImpl =
			new FundamentacaoPedidoImpl();

		fundamentacaoPedidoImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		fundamentacaoPedidoImpl.setFundamentacaoId(
			this.<Long>getColumnOriginalValue("fundamentacaoId"));
		fundamentacaoPedidoImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		fundamentacaoPedidoImpl.setFundamentacaoPedido(
			this.<String>getColumnOriginalValue("fundamentacaoPedido"));

		return fundamentacaoPedidoImpl;
	}

	@Override
	public int compareTo(FundamentacaoPedido fundamentacaoPedido) {
		long primaryKey = fundamentacaoPedido.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FundamentacaoPedido)) {
			return false;
		}

		FundamentacaoPedido fundamentacaoPedido = (FundamentacaoPedido)object;

		long primaryKey = fundamentacaoPedido.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FundamentacaoPedido> toCacheModel() {
		FundamentacaoPedidoCacheModel fundamentacaoPedidoCacheModel =
			new FundamentacaoPedidoCacheModel();

		fundamentacaoPedidoCacheModel.uuid = getUuid();

		String uuid = fundamentacaoPedidoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fundamentacaoPedidoCacheModel.uuid = null;
		}

		fundamentacaoPedidoCacheModel.fundamentacaoId = getFundamentacaoId();

		fundamentacaoPedidoCacheModel.propostaId = getPropostaId();

		fundamentacaoPedidoCacheModel.fundamentacaoPedido =
			getFundamentacaoPedido();

		String fundamentacaoPedido =
			fundamentacaoPedidoCacheModel.fundamentacaoPedido;

		if ((fundamentacaoPedido != null) &&
			(fundamentacaoPedido.length() == 0)) {

			fundamentacaoPedidoCacheModel.fundamentacaoPedido = null;
		}

		return fundamentacaoPedidoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FundamentacaoPedido, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FundamentacaoPedido, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FundamentacaoPedido, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(FundamentacaoPedido)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FundamentacaoPedido>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FundamentacaoPedido.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _fundamentacaoId;
	private long _propostaId;
	private String _fundamentacaoPedido;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FundamentacaoPedido, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FundamentacaoPedido)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("fundamentacaoId", _fundamentacaoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("fundamentacaoPedido", _fundamentacaoPedido);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("fundamentacaoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("fundamentacaoPedido", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FundamentacaoPedido _escapedModel;

}