/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.GarantiaProposta;
import br.com.seatecnologia.gdf.negocia.model.GarantiaPropostaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GarantiaProposta service. Represents a row in the &quot;GDF_GarantiaProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GarantiaPropostaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GarantiaPropostaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GarantiaPropostaImpl
 * @generated
 */
@JSON(strict = true)
public class GarantiaPropostaModelImpl
	extends BaseModelImpl<GarantiaProposta> implements GarantiaPropostaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a garantia proposta model instance should use the <code>GarantiaProposta</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_GarantiaProposta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"garantiaPropostaId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"garantiaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("garantiaPropostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("garantiaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_GarantiaProposta (uuid_ VARCHAR(75) null,garantiaPropostaId LONG not null primary key,propostaId LONG,garantiaId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_GarantiaProposta";

	public static final String ORDER_BY_JPQL =
		" ORDER BY garantiaProposta.garantiaPropostaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_GarantiaProposta.garantiaPropostaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GARANTIAPROPOSTAID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GarantiaPropostaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _garantiaPropostaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGarantiaPropostaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _garantiaPropostaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GarantiaProposta.class;
	}

	@Override
	public String getModelClassName() {
		return GarantiaProposta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GarantiaProposta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GarantiaProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GarantiaProposta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GarantiaProposta)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GarantiaProposta, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GarantiaProposta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GarantiaProposta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GarantiaProposta, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GarantiaProposta, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<GarantiaProposta, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<GarantiaProposta, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<GarantiaProposta, Object>>();

			attributeGetterFunctions.put("uuid", GarantiaProposta::getUuid);
			attributeGetterFunctions.put(
				"garantiaPropostaId", GarantiaProposta::getGarantiaPropostaId);
			attributeGetterFunctions.put(
				"propostaId", GarantiaProposta::getPropostaId);
			attributeGetterFunctions.put(
				"garantiaId", GarantiaProposta::getGarantiaId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<GarantiaProposta, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<GarantiaProposta, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<GarantiaProposta, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<GarantiaProposta, String>)
					GarantiaProposta::setUuid);
			attributeSetterBiConsumers.put(
				"garantiaPropostaId",
				(BiConsumer<GarantiaProposta, Long>)
					GarantiaProposta::setGarantiaPropostaId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<GarantiaProposta, Long>)
					GarantiaProposta::setPropostaId);
			attributeSetterBiConsumers.put(
				"garantiaId",
				(BiConsumer<GarantiaProposta, Long>)
					GarantiaProposta::setGarantiaId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getGarantiaPropostaId() {
		return _garantiaPropostaId;
	}

	@Override
	public void setGarantiaPropostaId(long garantiaPropostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_garantiaPropostaId = garantiaPropostaId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	@JSON
	@Override
	public long getGarantiaId() {
		return _garantiaId;
	}

	@Override
	public void setGarantiaId(long garantiaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_garantiaId = garantiaId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, GarantiaProposta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GarantiaProposta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GarantiaProposta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GarantiaPropostaImpl garantiaPropostaImpl = new GarantiaPropostaImpl();

		garantiaPropostaImpl.setUuid(getUuid());
		garantiaPropostaImpl.setGarantiaPropostaId(getGarantiaPropostaId());
		garantiaPropostaImpl.setPropostaId(getPropostaId());
		garantiaPropostaImpl.setGarantiaId(getGarantiaId());

		garantiaPropostaImpl.resetOriginalValues();

		return garantiaPropostaImpl;
	}

	@Override
	public GarantiaProposta cloneWithOriginalValues() {
		GarantiaPropostaImpl garantiaPropostaImpl = new GarantiaPropostaImpl();

		garantiaPropostaImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		garantiaPropostaImpl.setGarantiaPropostaId(
			this.<Long>getColumnOriginalValue("garantiaPropostaId"));
		garantiaPropostaImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		garantiaPropostaImpl.setGarantiaId(
			this.<Long>getColumnOriginalValue("garantiaId"));

		return garantiaPropostaImpl;
	}

	@Override
	public int compareTo(GarantiaProposta garantiaProposta) {
		long primaryKey = garantiaProposta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GarantiaProposta)) {
			return false;
		}

		GarantiaProposta garantiaProposta = (GarantiaProposta)object;

		long primaryKey = garantiaProposta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GarantiaProposta> toCacheModel() {
		GarantiaPropostaCacheModel garantiaPropostaCacheModel =
			new GarantiaPropostaCacheModel();

		garantiaPropostaCacheModel.uuid = getUuid();

		String uuid = garantiaPropostaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			garantiaPropostaCacheModel.uuid = null;
		}

		garantiaPropostaCacheModel.garantiaPropostaId = getGarantiaPropostaId();

		garantiaPropostaCacheModel.propostaId = getPropostaId();

		garantiaPropostaCacheModel.garantiaId = getGarantiaId();

		return garantiaPropostaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GarantiaProposta, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GarantiaProposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GarantiaProposta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(GarantiaProposta)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GarantiaProposta>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					GarantiaProposta.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _garantiaPropostaId;
	private long _propostaId;
	private long _garantiaId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GarantiaProposta, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GarantiaProposta)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("garantiaPropostaId", _garantiaPropostaId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("garantiaId", _garantiaId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("garantiaPropostaId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("garantiaId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GarantiaProposta _escapedModel;

}