/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Parcelamento;
import br.com.seatecnologia.gdf.negocia.model.ParcelamentoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Parcelamento service. Represents a row in the &quot;GDF_Parcelamento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParcelamentoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParcelamentoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParcelamentoImpl
 * @generated
 */
@JSON(strict = true)
public class ParcelamentoModelImpl
	extends BaseModelImpl<Parcelamento> implements ParcelamentoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parcelamento model instance should use the <code>Parcelamento</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_Parcelamento";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"parcelamentoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"numeroParcelas", Types.INTEGER},
		{"valorEntrada", Types.DOUBLE},
		{"dataPrimeiraParcela", Types.TIMESTAMP},
		{"valorPrimeiraParcela", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parcelamentoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("numeroParcelas", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("valorEntrada", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("dataPrimeiraParcela", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("valorPrimeiraParcela", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_Parcelamento (uuid_ VARCHAR(75) null,parcelamentoId LONG not null primary key,propostaId LONG,numeroParcelas INTEGER,valorEntrada DOUBLE,dataPrimeiraParcela DATE null,valorPrimeiraParcela DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table GDF_Parcelamento";

	public static final String ORDER_BY_JPQL =
		" ORDER BY parcelamento.parcelamentoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_Parcelamento.parcelamentoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARCELAMENTOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParcelamentoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _parcelamentoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParcelamentoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _parcelamentoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Parcelamento.class;
	}

	@Override
	public String getModelClassName() {
		return Parcelamento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parcelamento, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parcelamento, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parcelamento, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Parcelamento)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parcelamento, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parcelamento, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parcelamento)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parcelamento, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parcelamento, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Parcelamento, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Parcelamento, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Parcelamento, Object>>();

			attributeGetterFunctions.put("uuid", Parcelamento::getUuid);
			attributeGetterFunctions.put(
				"parcelamentoId", Parcelamento::getParcelamentoId);
			attributeGetterFunctions.put(
				"propostaId", Parcelamento::getPropostaId);
			attributeGetterFunctions.put(
				"numeroParcelas", Parcelamento::getNumeroParcelas);
			attributeGetterFunctions.put(
				"valorEntrada", Parcelamento::getValorEntrada);
			attributeGetterFunctions.put(
				"dataPrimeiraParcela", Parcelamento::getDataPrimeiraParcela);
			attributeGetterFunctions.put(
				"valorPrimeiraParcela", Parcelamento::getValorPrimeiraParcela);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Parcelamento, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Parcelamento, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Parcelamento, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Parcelamento, String>)Parcelamento::setUuid);
			attributeSetterBiConsumers.put(
				"parcelamentoId",
				(BiConsumer<Parcelamento, Long>)
					Parcelamento::setParcelamentoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<Parcelamento, Long>)Parcelamento::setPropostaId);
			attributeSetterBiConsumers.put(
				"numeroParcelas",
				(BiConsumer<Parcelamento, Integer>)
					Parcelamento::setNumeroParcelas);
			attributeSetterBiConsumers.put(
				"valorEntrada",
				(BiConsumer<Parcelamento, Double>)
					Parcelamento::setValorEntrada);
			attributeSetterBiConsumers.put(
				"dataPrimeiraParcela",
				(BiConsumer<Parcelamento, Date>)
					Parcelamento::setDataPrimeiraParcela);
			attributeSetterBiConsumers.put(
				"valorPrimeiraParcela",
				(BiConsumer<Parcelamento, Double>)
					Parcelamento::setValorPrimeiraParcela);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getParcelamentoId() {
		return _parcelamentoId;
	}

	@Override
	public void setParcelamentoId(long parcelamentoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parcelamentoId = parcelamentoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public int getNumeroParcelas() {
		return _numeroParcelas;
	}

	@Override
	public void setNumeroParcelas(int numeroParcelas) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numeroParcelas = numeroParcelas;
	}

	@JSON
	@Override
	public double getValorEntrada() {
		return _valorEntrada;
	}

	@Override
	public void setValorEntrada(double valorEntrada) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valorEntrada = valorEntrada;
	}

	@JSON
	@Override
	public Date getDataPrimeiraParcela() {
		return _dataPrimeiraParcela;
	}

	@Override
	public void setDataPrimeiraParcela(Date dataPrimeiraParcela) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataPrimeiraParcela = dataPrimeiraParcela;
	}

	@JSON
	@Override
	public double getValorPrimeiraParcela() {
		return _valorPrimeiraParcela;
	}

	@Override
	public void setValorPrimeiraParcela(double valorPrimeiraParcela) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valorPrimeiraParcela = valorPrimeiraParcela;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Parcelamento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Parcelamento toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Parcelamento>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParcelamentoImpl parcelamentoImpl = new ParcelamentoImpl();

		parcelamentoImpl.setUuid(getUuid());
		parcelamentoImpl.setParcelamentoId(getParcelamentoId());
		parcelamentoImpl.setPropostaId(getPropostaId());
		parcelamentoImpl.setNumeroParcelas(getNumeroParcelas());
		parcelamentoImpl.setValorEntrada(getValorEntrada());
		parcelamentoImpl.setDataPrimeiraParcela(getDataPrimeiraParcela());
		parcelamentoImpl.setValorPrimeiraParcela(getValorPrimeiraParcela());

		parcelamentoImpl.resetOriginalValues();

		return parcelamentoImpl;
	}

	@Override
	public Parcelamento cloneWithOriginalValues() {
		ParcelamentoImpl parcelamentoImpl = new ParcelamentoImpl();

		parcelamentoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		parcelamentoImpl.setParcelamentoId(
			this.<Long>getColumnOriginalValue("parcelamentoId"));
		parcelamentoImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		parcelamentoImpl.setNumeroParcelas(
			this.<Integer>getColumnOriginalValue("numeroParcelas"));
		parcelamentoImpl.setValorEntrada(
			this.<Double>getColumnOriginalValue("valorEntrada"));
		parcelamentoImpl.setDataPrimeiraParcela(
			this.<Date>getColumnOriginalValue("dataPrimeiraParcela"));
		parcelamentoImpl.setValorPrimeiraParcela(
			this.<Double>getColumnOriginalValue("valorPrimeiraParcela"));

		return parcelamentoImpl;
	}

	@Override
	public int compareTo(Parcelamento parcelamento) {
		long primaryKey = parcelamento.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Parcelamento)) {
			return false;
		}

		Parcelamento parcelamento = (Parcelamento)object;

		long primaryKey = parcelamento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Parcelamento> toCacheModel() {
		ParcelamentoCacheModel parcelamentoCacheModel =
			new ParcelamentoCacheModel();

		parcelamentoCacheModel.uuid = getUuid();

		String uuid = parcelamentoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			parcelamentoCacheModel.uuid = null;
		}

		parcelamentoCacheModel.parcelamentoId = getParcelamentoId();

		parcelamentoCacheModel.propostaId = getPropostaId();

		parcelamentoCacheModel.numeroParcelas = getNumeroParcelas();

		parcelamentoCacheModel.valorEntrada = getValorEntrada();

		Date dataPrimeiraParcela = getDataPrimeiraParcela();

		if (dataPrimeiraParcela != null) {
			parcelamentoCacheModel.dataPrimeiraParcela =
				dataPrimeiraParcela.getTime();
		}
		else {
			parcelamentoCacheModel.dataPrimeiraParcela = Long.MIN_VALUE;
		}

		parcelamentoCacheModel.valorPrimeiraParcela = getValorPrimeiraParcela();

		return parcelamentoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parcelamento, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parcelamento, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parcelamento, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Parcelamento)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Parcelamento>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Parcelamento.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _parcelamentoId;
	private long _propostaId;
	private int _numeroParcelas;
	private double _valorEntrada;
	private Date _dataPrimeiraParcela;
	private double _valorPrimeiraParcela;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Parcelamento, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Parcelamento)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("parcelamentoId", _parcelamentoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("numeroParcelas", _numeroParcelas);
		_columnOriginalValues.put("valorEntrada", _valorEntrada);
		_columnOriginalValues.put("dataPrimeiraParcela", _dataPrimeiraParcela);
		_columnOriginalValues.put(
			"valorPrimeiraParcela", _valorPrimeiraParcela);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("parcelamentoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("numeroParcelas", 8L);

		columnBitmasks.put("valorEntrada", 16L);

		columnBitmasks.put("dataPrimeiraParcela", 32L);

		columnBitmasks.put("valorPrimeiraParcela", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Parcelamento _escapedModel;

}