/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.Procuracao;
import br.com.seatecnologia.gdf.negocia.model.ProcuracaoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Procuracao service. Represents a row in the &quot;GDF_Procuracao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProcuracaoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProcuracaoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProcuracaoImpl
 * @generated
 */
@JSON(strict = true)
public class ProcuracaoModelImpl
	extends BaseModelImpl<Procuracao> implements ProcuracaoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a procuracao model instance should use the <code>Procuracao</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_Procuracao";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"procuracaoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"procuracao", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("procuracaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("procuracao", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_Procuracao (uuid_ VARCHAR(75) null,procuracaoId LONG not null primary key,propostaId LONG,procuracao LONG)";

	public static final String TABLE_SQL_DROP = "drop table GDF_Procuracao";

	public static final String ORDER_BY_JPQL =
		" ORDER BY procuracao.procuracaoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_Procuracao.procuracaoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROCURACAOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProcuracaoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _procuracaoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProcuracaoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _procuracaoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Procuracao.class;
	}

	@Override
	public String getModelClassName() {
		return Procuracao.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Procuracao, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Procuracao, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Procuracao, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Procuracao)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Procuracao, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Procuracao, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Procuracao)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Procuracao, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Procuracao, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Procuracao, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Procuracao, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Procuracao, Object>>();

			attributeGetterFunctions.put("uuid", Procuracao::getUuid);
			attributeGetterFunctions.put(
				"procuracaoId", Procuracao::getProcuracaoId);
			attributeGetterFunctions.put(
				"propostaId", Procuracao::getPropostaId);
			attributeGetterFunctions.put(
				"procuracao", Procuracao::getProcuracao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Procuracao, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Procuracao, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Procuracao, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Procuracao, String>)Procuracao::setUuid);
			attributeSetterBiConsumers.put(
				"procuracaoId",
				(BiConsumer<Procuracao, Long>)Procuracao::setProcuracaoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<Procuracao, Long>)Procuracao::setPropostaId);
			attributeSetterBiConsumers.put(
				"procuracao",
				(BiConsumer<Procuracao, Long>)Procuracao::setProcuracao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getProcuracaoId() {
		return _procuracaoId;
	}

	@Override
	public void setProcuracaoId(long procuracaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_procuracaoId = procuracaoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public long getProcuracao() {
		return _procuracao;
	}

	@Override
	public void setProcuracao(long procuracao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_procuracao = procuracao;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Procuracao.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Procuracao toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Procuracao>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProcuracaoImpl procuracaoImpl = new ProcuracaoImpl();

		procuracaoImpl.setUuid(getUuid());
		procuracaoImpl.setProcuracaoId(getProcuracaoId());
		procuracaoImpl.setPropostaId(getPropostaId());
		procuracaoImpl.setProcuracao(getProcuracao());

		procuracaoImpl.resetOriginalValues();

		return procuracaoImpl;
	}

	@Override
	public Procuracao cloneWithOriginalValues() {
		ProcuracaoImpl procuracaoImpl = new ProcuracaoImpl();

		procuracaoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		procuracaoImpl.setProcuracaoId(
			this.<Long>getColumnOriginalValue("procuracaoId"));
		procuracaoImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		procuracaoImpl.setProcuracao(
			this.<Long>getColumnOriginalValue("procuracao"));

		return procuracaoImpl;
	}

	@Override
	public int compareTo(Procuracao procuracao) {
		long primaryKey = procuracao.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Procuracao)) {
			return false;
		}

		Procuracao procuracao = (Procuracao)object;

		long primaryKey = procuracao.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Procuracao> toCacheModel() {
		ProcuracaoCacheModel procuracaoCacheModel = new ProcuracaoCacheModel();

		procuracaoCacheModel.uuid = getUuid();

		String uuid = procuracaoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			procuracaoCacheModel.uuid = null;
		}

		procuracaoCacheModel.procuracaoId = getProcuracaoId();

		procuracaoCacheModel.propostaId = getPropostaId();

		procuracaoCacheModel.procuracao = getProcuracao();

		return procuracaoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Procuracao, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Procuracao, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Procuracao, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Procuracao)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Procuracao>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Procuracao.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _procuracaoId;
	private long _propostaId;
	private long _procuracao;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Procuracao, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Procuracao)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("procuracaoId", _procuracaoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("procuracao", _procuracao);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("procuracaoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("procuracao", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Procuracao _escapedModel;

}