/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.QualificacaoContribuinte;
import br.com.seatecnologia.gdf.negocia.service.QualificacaoContribuinteLocalServiceUtil;

/**
 * The extended model base implementation for the QualificacaoContribuinte service. Represents a row in the &quot;GDF_QualificacaoContribuinte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QualificacaoContribuinteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QualificacaoContribuinteImpl
 * @see QualificacaoContribuinte
 * @generated
 */
public abstract class QualificacaoContribuinteBaseImpl
	extends QualificacaoContribuinteModelImpl
	implements QualificacaoContribuinte {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qualificacao contribuinte model instance should use the <code>QualificacaoContribuinte</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			QualificacaoContribuinteLocalServiceUtil.
				addQualificacaoContribuinte(this);
		}
		else {
			QualificacaoContribuinteLocalServiceUtil.
				updateQualificacaoContribuinte(this);
		}
	}

}