/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.QualificacaoContribuinte;
import br.com.seatecnologia.gdf.negocia.model.QualificacaoContribuinteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the QualificacaoContribuinte service. Represents a row in the &quot;GDF_QualificacaoContribuinte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>QualificacaoContribuinteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link QualificacaoContribuinteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QualificacaoContribuinteImpl
 * @generated
 */
@JSON(strict = true)
public class QualificacaoContribuinteModelImpl
	extends BaseModelImpl<QualificacaoContribuinte>
	implements QualificacaoContribuinteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a qualificacao contribuinte model instance should use the <code>QualificacaoContribuinte</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_QualificacaoContribuinte";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"qualificacaoContribuinteId", Types.BIGINT},
		{"dadosContribuinteId", Types.BIGINT}, {"qualificacaoId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"userId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"tipoQualificacao", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("qualificacaoContribuinteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dadosContribuinteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("qualificacaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipoQualificacao", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_QualificacaoContribuinte (uuid_ VARCHAR(75) null,qualificacaoContribuinteId LONG not null primary key,dadosContribuinteId LONG,qualificacaoId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,groupId LONG,companyId LONG,tipoQualificacao VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table GDF_QualificacaoContribuinte";

	public static final String ORDER_BY_JPQL =
		" ORDER BY qualificacaoContribuinte.qualificacaoContribuinteId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_QualificacaoContribuinte.qualificacaoContribuinteId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long QUALIFICACAOCONTRIBUINTEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public QualificacaoContribuinteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _qualificacaoContribuinteId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setQualificacaoContribuinteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _qualificacaoContribuinteId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return QualificacaoContribuinte.class;
	}

	@Override
	public String getModelClassName() {
		return QualificacaoContribuinte.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<QualificacaoContribuinte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<QualificacaoContribuinte, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QualificacaoContribuinte, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((QualificacaoContribuinte)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<QualificacaoContribuinte, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<QualificacaoContribuinte, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(QualificacaoContribuinte)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<QualificacaoContribuinte, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<QualificacaoContribuinte, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<QualificacaoContribuinte, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<QualificacaoContribuinte, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<QualificacaoContribuinte, Object>>();

			attributeGetterFunctions.put(
				"uuid", QualificacaoContribuinte::getUuid);
			attributeGetterFunctions.put(
				"qualificacaoContribuinteId",
				QualificacaoContribuinte::getQualificacaoContribuinteId);
			attributeGetterFunctions.put(
				"dadosContribuinteId",
				QualificacaoContribuinte::getDadosContribuinteId);
			attributeGetterFunctions.put(
				"qualificacaoId", QualificacaoContribuinte::getQualificacaoId);
			attributeGetterFunctions.put(
				"createDate", QualificacaoContribuinte::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", QualificacaoContribuinte::getModifiedDate);
			attributeGetterFunctions.put(
				"userId", QualificacaoContribuinte::getUserId);
			attributeGetterFunctions.put(
				"groupId", QualificacaoContribuinte::getGroupId);
			attributeGetterFunctions.put(
				"companyId", QualificacaoContribuinte::getCompanyId);
			attributeGetterFunctions.put(
				"tipoQualificacao",
				QualificacaoContribuinte::getTipoQualificacao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<QualificacaoContribuinte, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<QualificacaoContribuinte, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<QualificacaoContribuinte, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<QualificacaoContribuinte, String>)
					QualificacaoContribuinte::setUuid);
			attributeSetterBiConsumers.put(
				"qualificacaoContribuinteId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setQualificacaoContribuinteId);
			attributeSetterBiConsumers.put(
				"dadosContribuinteId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setDadosContribuinteId);
			attributeSetterBiConsumers.put(
				"qualificacaoId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setQualificacaoId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<QualificacaoContribuinte, Date>)
					QualificacaoContribuinte::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<QualificacaoContribuinte, Date>)
					QualificacaoContribuinte::setModifiedDate);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setUserId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<QualificacaoContribuinte, Long>)
					QualificacaoContribuinte::setCompanyId);
			attributeSetterBiConsumers.put(
				"tipoQualificacao",
				(BiConsumer<QualificacaoContribuinte, String>)
					QualificacaoContribuinte::setTipoQualificacao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getQualificacaoContribuinteId() {
		return _qualificacaoContribuinteId;
	}

	@Override
	public void setQualificacaoContribuinteId(long qualificacaoContribuinteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qualificacaoContribuinteId = qualificacaoContribuinteId;
	}

	@JSON
	@Override
	public long getDadosContribuinteId() {
		return _dadosContribuinteId;
	}

	@Override
	public void setDadosContribuinteId(long dadosContribuinteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dadosContribuinteId = dadosContribuinteId;
	}

	@JSON
	@Override
	public long getQualificacaoId() {
		return _qualificacaoId;
	}

	@Override
	public void setQualificacaoId(long qualificacaoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_qualificacaoId = qualificacaoId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public String getTipoQualificacao() {
		if (_tipoQualificacao == null) {
			return "";
		}
		else {
			return _tipoQualificacao;
		}
	}

	@Override
	public void setTipoQualificacao(String tipoQualificacao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipoQualificacao = tipoQualificacao;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				QualificacaoContribuinte.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), QualificacaoContribuinte.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public QualificacaoContribuinte toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, QualificacaoContribuinte>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		QualificacaoContribuinteImpl qualificacaoContribuinteImpl =
			new QualificacaoContribuinteImpl();

		qualificacaoContribuinteImpl.setUuid(getUuid());
		qualificacaoContribuinteImpl.setQualificacaoContribuinteId(
			getQualificacaoContribuinteId());
		qualificacaoContribuinteImpl.setDadosContribuinteId(
			getDadosContribuinteId());
		qualificacaoContribuinteImpl.setQualificacaoId(getQualificacaoId());
		qualificacaoContribuinteImpl.setCreateDate(getCreateDate());
		qualificacaoContribuinteImpl.setModifiedDate(getModifiedDate());
		qualificacaoContribuinteImpl.setUserId(getUserId());
		qualificacaoContribuinteImpl.setGroupId(getGroupId());
		qualificacaoContribuinteImpl.setCompanyId(getCompanyId());
		qualificacaoContribuinteImpl.setTipoQualificacao(getTipoQualificacao());

		qualificacaoContribuinteImpl.resetOriginalValues();

		return qualificacaoContribuinteImpl;
	}

	@Override
	public QualificacaoContribuinte cloneWithOriginalValues() {
		QualificacaoContribuinteImpl qualificacaoContribuinteImpl =
			new QualificacaoContribuinteImpl();

		qualificacaoContribuinteImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		qualificacaoContribuinteImpl.setQualificacaoContribuinteId(
			this.<Long>getColumnOriginalValue("qualificacaoContribuinteId"));
		qualificacaoContribuinteImpl.setDadosContribuinteId(
			this.<Long>getColumnOriginalValue("dadosContribuinteId"));
		qualificacaoContribuinteImpl.setQualificacaoId(
			this.<Long>getColumnOriginalValue("qualificacaoId"));
		qualificacaoContribuinteImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		qualificacaoContribuinteImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		qualificacaoContribuinteImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		qualificacaoContribuinteImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		qualificacaoContribuinteImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		qualificacaoContribuinteImpl.setTipoQualificacao(
			this.<String>getColumnOriginalValue("tipoQualificacao"));

		return qualificacaoContribuinteImpl;
	}

	@Override
	public int compareTo(QualificacaoContribuinte qualificacaoContribuinte) {
		long primaryKey = qualificacaoContribuinte.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof QualificacaoContribuinte)) {
			return false;
		}

		QualificacaoContribuinte qualificacaoContribuinte =
			(QualificacaoContribuinte)object;

		long primaryKey = qualificacaoContribuinte.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<QualificacaoContribuinte> toCacheModel() {
		QualificacaoContribuinteCacheModel qualificacaoContribuinteCacheModel =
			new QualificacaoContribuinteCacheModel();

		qualificacaoContribuinteCacheModel.uuid = getUuid();

		String uuid = qualificacaoContribuinteCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			qualificacaoContribuinteCacheModel.uuid = null;
		}

		qualificacaoContribuinteCacheModel.qualificacaoContribuinteId =
			getQualificacaoContribuinteId();

		qualificacaoContribuinteCacheModel.dadosContribuinteId =
			getDadosContribuinteId();

		qualificacaoContribuinteCacheModel.qualificacaoId = getQualificacaoId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			qualificacaoContribuinteCacheModel.createDate =
				createDate.getTime();
		}
		else {
			qualificacaoContribuinteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			qualificacaoContribuinteCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			qualificacaoContribuinteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		qualificacaoContribuinteCacheModel.userId = getUserId();

		qualificacaoContribuinteCacheModel.groupId = getGroupId();

		qualificacaoContribuinteCacheModel.companyId = getCompanyId();

		qualificacaoContribuinteCacheModel.tipoQualificacao =
			getTipoQualificacao();

		String tipoQualificacao =
			qualificacaoContribuinteCacheModel.tipoQualificacao;

		if ((tipoQualificacao != null) && (tipoQualificacao.length() == 0)) {
			qualificacaoContribuinteCacheModel.tipoQualificacao = null;
		}

		return qualificacaoContribuinteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<QualificacaoContribuinte, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<QualificacaoContribuinte, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<QualificacaoContribuinte, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(QualificacaoContribuinte)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, QualificacaoContribuinte>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						QualificacaoContribuinte.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _qualificacaoContribuinteId;
	private long _dadosContribuinteId;
	private long _qualificacaoId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _userId;
	private long _groupId;
	private long _companyId;
	private String _tipoQualificacao;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<QualificacaoContribuinte, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((QualificacaoContribuinte)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"qualificacaoContribuinteId", _qualificacaoContribuinteId);
		_columnOriginalValues.put("dadosContribuinteId", _dadosContribuinteId);
		_columnOriginalValues.put("qualificacaoId", _qualificacaoId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("tipoQualificacao", _tipoQualificacao);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("qualificacaoContribuinteId", 2L);

		columnBitmasks.put("dadosContribuinteId", 4L);

		columnBitmasks.put("qualificacaoId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("groupId", 128L);

		columnBitmasks.put("companyId", 256L);

		columnBitmasks.put("tipoQualificacao", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private QualificacaoContribuinte _escapedModel;

}