/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.RelacaoCredor;
import br.com.seatecnologia.gdf.negocia.service.RelacaoCredorLocalServiceUtil;

/**
 * The extended model base implementation for the RelacaoCredor service. Represents a row in the &quot;GDF_RelacaoCredor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RelacaoCredorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RelacaoCredorImpl
 * @see RelacaoCredor
 * @generated
 */
public abstract class RelacaoCredorBaseImpl
	extends RelacaoCredorModelImpl implements RelacaoCredor {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a relacao credor model instance should use the <code>RelacaoCredor</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RelacaoCredorLocalServiceUtil.addRelacaoCredor(this);
		}
		else {
			RelacaoCredorLocalServiceUtil.updateRelacaoCredor(this);
		}
	}

}