/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.RelacaoCredor;
import br.com.seatecnologia.gdf.negocia.model.RelacaoCredorModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RelacaoCredor service. Represents a row in the &quot;GDF_RelacaoCredor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RelacaoCredorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RelacaoCredorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RelacaoCredorImpl
 * @generated
 */
@JSON(strict = true)
public class RelacaoCredorModelImpl
	extends BaseModelImpl<RelacaoCredor> implements RelacaoCredorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a relacao credor model instance should use the <code>RelacaoCredor</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_RelacaoCredor";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"credorId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"nomeCredor", Types.VARCHAR},
		{"naturezaCredito", Types.VARCHAR},
		{"classificacaoCredito", Types.VARCHAR},
		{"valorAtualizado", Types.DOUBLE}, {"referenciaContabil", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("credorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nomeCredor", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("naturezaCredito", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classificacaoCredito", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valorAtualizado", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("referenciaContabil", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_RelacaoCredor (uuid_ VARCHAR(75) null,credorId LONG not null primary key,propostaId LONG,nomeCredor VARCHAR(1000) null,naturezaCredito VARCHAR(255) null,classificacaoCredito VARCHAR(255) null,valorAtualizado DOUBLE,referenciaContabil VARCHAR(1000) null)";

	public static final String TABLE_SQL_DROP = "drop table GDF_RelacaoCredor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY relacaoCredor.credorId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_RelacaoCredor.credorId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREDORID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RelacaoCredorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _credorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCredorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _credorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RelacaoCredor.class;
	}

	@Override
	public String getModelClassName() {
		return RelacaoCredor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RelacaoCredor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RelacaoCredor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RelacaoCredor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RelacaoCredor)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RelacaoCredor, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RelacaoCredor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RelacaoCredor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RelacaoCredor, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RelacaoCredor, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RelacaoCredor, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RelacaoCredor, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RelacaoCredor, Object>>();

			attributeGetterFunctions.put("uuid", RelacaoCredor::getUuid);
			attributeGetterFunctions.put(
				"credorId", RelacaoCredor::getCredorId);
			attributeGetterFunctions.put(
				"propostaId", RelacaoCredor::getPropostaId);
			attributeGetterFunctions.put(
				"nomeCredor", RelacaoCredor::getNomeCredor);
			attributeGetterFunctions.put(
				"naturezaCredito", RelacaoCredor::getNaturezaCredito);
			attributeGetterFunctions.put(
				"classificacaoCredito", RelacaoCredor::getClassificacaoCredito);
			attributeGetterFunctions.put(
				"valorAtualizado", RelacaoCredor::getValorAtualizado);
			attributeGetterFunctions.put(
				"referenciaContabil", RelacaoCredor::getReferenciaContabil);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<RelacaoCredor, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RelacaoCredor, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<RelacaoCredor, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<RelacaoCredor, String>)RelacaoCredor::setUuid);
			attributeSetterBiConsumers.put(
				"credorId",
				(BiConsumer<RelacaoCredor, Long>)RelacaoCredor::setCredorId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<RelacaoCredor, Long>)RelacaoCredor::setPropostaId);
			attributeSetterBiConsumers.put(
				"nomeCredor",
				(BiConsumer<RelacaoCredor, String>)
					RelacaoCredor::setNomeCredor);
			attributeSetterBiConsumers.put(
				"naturezaCredito",
				(BiConsumer<RelacaoCredor, String>)
					RelacaoCredor::setNaturezaCredito);
			attributeSetterBiConsumers.put(
				"classificacaoCredito",
				(BiConsumer<RelacaoCredor, String>)
					RelacaoCredor::setClassificacaoCredito);
			attributeSetterBiConsumers.put(
				"valorAtualizado",
				(BiConsumer<RelacaoCredor, Double>)
					RelacaoCredor::setValorAtualizado);
			attributeSetterBiConsumers.put(
				"referenciaContabil",
				(BiConsumer<RelacaoCredor, String>)
					RelacaoCredor::setReferenciaContabil);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCredorId() {
		return _credorId;
	}

	@Override
	public void setCredorId(long credorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_credorId = credorId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public String getNomeCredor() {
		if (_nomeCredor == null) {
			return "";
		}
		else {
			return _nomeCredor;
		}
	}

	@Override
	public void setNomeCredor(String nomeCredor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeCredor = nomeCredor;
	}

	@JSON
	@Override
	public String getNaturezaCredito() {
		if (_naturezaCredito == null) {
			return "";
		}
		else {
			return _naturezaCredito;
		}
	}

	@Override
	public void setNaturezaCredito(String naturezaCredito) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_naturezaCredito = naturezaCredito;
	}

	@JSON
	@Override
	public String getClassificacaoCredito() {
		if (_classificacaoCredito == null) {
			return "";
		}
		else {
			return _classificacaoCredito;
		}
	}

	@Override
	public void setClassificacaoCredito(String classificacaoCredito) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classificacaoCredito = classificacaoCredito;
	}

	@JSON
	@Override
	public double getValorAtualizado() {
		return _valorAtualizado;
	}

	@Override
	public void setValorAtualizado(double valorAtualizado) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valorAtualizado = valorAtualizado;
	}

	@JSON
	@Override
	public String getReferenciaContabil() {
		if (_referenciaContabil == null) {
			return "";
		}
		else {
			return _referenciaContabil;
		}
	}

	@Override
	public void setReferenciaContabil(String referenciaContabil) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenciaContabil = referenciaContabil;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RelacaoCredor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RelacaoCredor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RelacaoCredor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RelacaoCredorImpl relacaoCredorImpl = new RelacaoCredorImpl();

		relacaoCredorImpl.setUuid(getUuid());
		relacaoCredorImpl.setCredorId(getCredorId());
		relacaoCredorImpl.setPropostaId(getPropostaId());
		relacaoCredorImpl.setNomeCredor(getNomeCredor());
		relacaoCredorImpl.setNaturezaCredito(getNaturezaCredito());
		relacaoCredorImpl.setClassificacaoCredito(getClassificacaoCredito());
		relacaoCredorImpl.setValorAtualizado(getValorAtualizado());
		relacaoCredorImpl.setReferenciaContabil(getReferenciaContabil());

		relacaoCredorImpl.resetOriginalValues();

		return relacaoCredorImpl;
	}

	@Override
	public RelacaoCredor cloneWithOriginalValues() {
		RelacaoCredorImpl relacaoCredorImpl = new RelacaoCredorImpl();

		relacaoCredorImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		relacaoCredorImpl.setCredorId(
			this.<Long>getColumnOriginalValue("credorId"));
		relacaoCredorImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		relacaoCredorImpl.setNomeCredor(
			this.<String>getColumnOriginalValue("nomeCredor"));
		relacaoCredorImpl.setNaturezaCredito(
			this.<String>getColumnOriginalValue("naturezaCredito"));
		relacaoCredorImpl.setClassificacaoCredito(
			this.<String>getColumnOriginalValue("classificacaoCredito"));
		relacaoCredorImpl.setValorAtualizado(
			this.<Double>getColumnOriginalValue("valorAtualizado"));
		relacaoCredorImpl.setReferenciaContabil(
			this.<String>getColumnOriginalValue("referenciaContabil"));

		return relacaoCredorImpl;
	}

	@Override
	public int compareTo(RelacaoCredor relacaoCredor) {
		long primaryKey = relacaoCredor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RelacaoCredor)) {
			return false;
		}

		RelacaoCredor relacaoCredor = (RelacaoCredor)object;

		long primaryKey = relacaoCredor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RelacaoCredor> toCacheModel() {
		RelacaoCredorCacheModel relacaoCredorCacheModel =
			new RelacaoCredorCacheModel();

		relacaoCredorCacheModel.uuid = getUuid();

		String uuid = relacaoCredorCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			relacaoCredorCacheModel.uuid = null;
		}

		relacaoCredorCacheModel.credorId = getCredorId();

		relacaoCredorCacheModel.propostaId = getPropostaId();

		relacaoCredorCacheModel.nomeCredor = getNomeCredor();

		String nomeCredor = relacaoCredorCacheModel.nomeCredor;

		if ((nomeCredor != null) && (nomeCredor.length() == 0)) {
			relacaoCredorCacheModel.nomeCredor = null;
		}

		relacaoCredorCacheModel.naturezaCredito = getNaturezaCredito();

		String naturezaCredito = relacaoCredorCacheModel.naturezaCredito;

		if ((naturezaCredito != null) && (naturezaCredito.length() == 0)) {
			relacaoCredorCacheModel.naturezaCredito = null;
		}

		relacaoCredorCacheModel.classificacaoCredito =
			getClassificacaoCredito();

		String classificacaoCredito =
			relacaoCredorCacheModel.classificacaoCredito;

		if ((classificacaoCredito != null) &&
			(classificacaoCredito.length() == 0)) {

			relacaoCredorCacheModel.classificacaoCredito = null;
		}

		relacaoCredorCacheModel.valorAtualizado = getValorAtualizado();

		relacaoCredorCacheModel.referenciaContabil = getReferenciaContabil();

		String referenciaContabil = relacaoCredorCacheModel.referenciaContabil;

		if ((referenciaContabil != null) &&
			(referenciaContabil.length() == 0)) {

			relacaoCredorCacheModel.referenciaContabil = null;
		}

		return relacaoCredorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RelacaoCredor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RelacaoCredor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RelacaoCredor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((RelacaoCredor)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RelacaoCredor>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RelacaoCredor.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _credorId;
	private long _propostaId;
	private String _nomeCredor;
	private String _naturezaCredito;
	private String _classificacaoCredito;
	private double _valorAtualizado;
	private String _referenciaContabil;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RelacaoCredor, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RelacaoCredor)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("credorId", _credorId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("nomeCredor", _nomeCredor);
		_columnOriginalValues.put("naturezaCredito", _naturezaCredito);
		_columnOriginalValues.put(
			"classificacaoCredito", _classificacaoCredito);
		_columnOriginalValues.put("valorAtualizado", _valorAtualizado);
		_columnOriginalValues.put("referenciaContabil", _referenciaContabil);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("credorId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("nomeCredor", 8L);

		columnBitmasks.put("naturezaCredito", 16L);

		columnBitmasks.put("classificacaoCredito", 32L);

		columnBitmasks.put("valorAtualizado", 64L);

		columnBitmasks.put("referenciaContabil", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RelacaoCredor _escapedModel;

}