/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.TermoAssinado;
import br.com.seatecnologia.gdf.negocia.service.TermoAssinadoLocalServiceUtil;

/**
 * The extended model base implementation for the TermoAssinado service. Represents a row in the &quot;GDF_TermoAssinado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermoAssinadoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermoAssinadoImpl
 * @see TermoAssinado
 * @generated
 */
public abstract class TermoAssinadoBaseImpl
	extends TermoAssinadoModelImpl implements TermoAssinado {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a termo assinado model instance should use the <code>TermoAssinado</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TermoAssinadoLocalServiceUtil.addTermoAssinado(this);
		}
		else {
			TermoAssinadoLocalServiceUtil.updateTermoAssinado(this);
		}
	}

}