/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model.impl;

import br.com.seatecnologia.gdf.negocia.model.TermoAssinado;
import br.com.seatecnologia.gdf.negocia.model.TermoAssinadoModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TermoAssinado service. Represents a row in the &quot;GDF_TermoAssinado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TermoAssinadoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TermoAssinadoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TermoAssinadoImpl
 * @generated
 */
@JSON(strict = true)
public class TermoAssinadoModelImpl
	extends BaseModelImpl<TermoAssinado> implements TermoAssinadoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a termo assinado model instance should use the <code>TermoAssinado</code> interface instead.
	 */
	public static final String TABLE_NAME = "GDF_TermoAssinado";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"termoId", Types.BIGINT},
		{"propostaId", Types.BIGINT}, {"urlTermo", Types.VARCHAR},
		{"arquivoPdf", Types.VARCHAR}, {"parte", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("termoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("propostaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("urlTermo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("arquivoPdf", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parte", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GDF_TermoAssinado (uuid_ VARCHAR(75) null,termoId LONG not null primary key,propostaId LONG,urlTermo VARCHAR(255) null,arquivoPdf VARCHAR(500) null,parte VARCHAR(255) null)";

	public static final String TABLE_SQL_DROP = "drop table GDF_TermoAssinado";

	public static final String ORDER_BY_JPQL =
		" ORDER BY termoAssinado.termoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GDF_TermoAssinado.termoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROPOSTAID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERMOID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TermoAssinadoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _termoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTermoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _termoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TermoAssinado.class;
	}

	@Override
	public String getModelClassName() {
		return TermoAssinado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TermoAssinado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TermoAssinado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TermoAssinado, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TermoAssinado)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TermoAssinado, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TermoAssinado, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TermoAssinado)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TermoAssinado, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TermoAssinado, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TermoAssinado, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TermoAssinado, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<TermoAssinado, Object>>();

			attributeGetterFunctions.put("uuid", TermoAssinado::getUuid);
			attributeGetterFunctions.put("termoId", TermoAssinado::getTermoId);
			attributeGetterFunctions.put(
				"propostaId", TermoAssinado::getPropostaId);
			attributeGetterFunctions.put(
				"urlTermo", TermoAssinado::getUrlTermo);
			attributeGetterFunctions.put(
				"arquivoPdf", TermoAssinado::getArquivoPdf);
			attributeGetterFunctions.put("parte", TermoAssinado::getParte);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TermoAssinado, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TermoAssinado, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<TermoAssinado, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<TermoAssinado, String>)TermoAssinado::setUuid);
			attributeSetterBiConsumers.put(
				"termoId",
				(BiConsumer<TermoAssinado, Long>)TermoAssinado::setTermoId);
			attributeSetterBiConsumers.put(
				"propostaId",
				(BiConsumer<TermoAssinado, Long>)TermoAssinado::setPropostaId);
			attributeSetterBiConsumers.put(
				"urlTermo",
				(BiConsumer<TermoAssinado, String>)TermoAssinado::setUrlTermo);
			attributeSetterBiConsumers.put(
				"arquivoPdf",
				(BiConsumer<TermoAssinado, String>)
					TermoAssinado::setArquivoPdf);
			attributeSetterBiConsumers.put(
				"parte",
				(BiConsumer<TermoAssinado, String>)TermoAssinado::setParte);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTermoId() {
		return _termoId;
	}

	@Override
	public void setTermoId(long termoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_termoId = termoId;
	}

	@JSON
	@Override
	public long getPropostaId() {
		return _propostaId;
	}

	@Override
	public void setPropostaId(long propostaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_propostaId = propostaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPropostaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("propostaId"));
	}

	@JSON
	@Override
	public String getUrlTermo() {
		if (_urlTermo == null) {
			return "";
		}
		else {
			return _urlTermo;
		}
	}

	@Override
	public void setUrlTermo(String urlTermo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_urlTermo = urlTermo;
	}

	@JSON
	@Override
	public String getArquivoPdf() {
		if (_arquivoPdf == null) {
			return "";
		}
		else {
			return _arquivoPdf;
		}
	}

	@Override
	public void setArquivoPdf(String arquivoPdf) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_arquivoPdf = arquivoPdf;
	}

	@JSON
	@Override
	public String getParte() {
		if (_parte == null) {
			return "";
		}
		else {
			return _parte;
		}
	}

	@Override
	public void setParte(String parte) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parte = parte;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TermoAssinado.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TermoAssinado toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TermoAssinado>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TermoAssinadoImpl termoAssinadoImpl = new TermoAssinadoImpl();

		termoAssinadoImpl.setUuid(getUuid());
		termoAssinadoImpl.setTermoId(getTermoId());
		termoAssinadoImpl.setPropostaId(getPropostaId());
		termoAssinadoImpl.setUrlTermo(getUrlTermo());
		termoAssinadoImpl.setArquivoPdf(getArquivoPdf());
		termoAssinadoImpl.setParte(getParte());

		termoAssinadoImpl.resetOriginalValues();

		return termoAssinadoImpl;
	}

	@Override
	public TermoAssinado cloneWithOriginalValues() {
		TermoAssinadoImpl termoAssinadoImpl = new TermoAssinadoImpl();

		termoAssinadoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		termoAssinadoImpl.setTermoId(
			this.<Long>getColumnOriginalValue("termoId"));
		termoAssinadoImpl.setPropostaId(
			this.<Long>getColumnOriginalValue("propostaId"));
		termoAssinadoImpl.setUrlTermo(
			this.<String>getColumnOriginalValue("urlTermo"));
		termoAssinadoImpl.setArquivoPdf(
			this.<String>getColumnOriginalValue("arquivoPdf"));
		termoAssinadoImpl.setParte(
			this.<String>getColumnOriginalValue("parte"));

		return termoAssinadoImpl;
	}

	@Override
	public int compareTo(TermoAssinado termoAssinado) {
		long primaryKey = termoAssinado.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TermoAssinado)) {
			return false;
		}

		TermoAssinado termoAssinado = (TermoAssinado)object;

		long primaryKey = termoAssinado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TermoAssinado> toCacheModel() {
		TermoAssinadoCacheModel termoAssinadoCacheModel =
			new TermoAssinadoCacheModel();

		termoAssinadoCacheModel.uuid = getUuid();

		String uuid = termoAssinadoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			termoAssinadoCacheModel.uuid = null;
		}

		termoAssinadoCacheModel.termoId = getTermoId();

		termoAssinadoCacheModel.propostaId = getPropostaId();

		termoAssinadoCacheModel.urlTermo = getUrlTermo();

		String urlTermo = termoAssinadoCacheModel.urlTermo;

		if ((urlTermo != null) && (urlTermo.length() == 0)) {
			termoAssinadoCacheModel.urlTermo = null;
		}

		termoAssinadoCacheModel.arquivoPdf = getArquivoPdf();

		String arquivoPdf = termoAssinadoCacheModel.arquivoPdf;

		if ((arquivoPdf != null) && (arquivoPdf.length() == 0)) {
			termoAssinadoCacheModel.arquivoPdf = null;
		}

		termoAssinadoCacheModel.parte = getParte();

		String parte = termoAssinadoCacheModel.parte;

		if ((parte != null) && (parte.length() == 0)) {
			termoAssinadoCacheModel.parte = null;
		}

		return termoAssinadoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TermoAssinado, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TermoAssinado, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TermoAssinado, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TermoAssinado)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TermoAssinado>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TermoAssinado.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _termoId;
	private long _propostaId;
	private String _urlTermo;
	private String _arquivoPdf;
	private String _parte;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TermoAssinado, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TermoAssinado)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("termoId", _termoId);
		_columnOriginalValues.put("propostaId", _propostaId);
		_columnOriginalValues.put("urlTermo", _urlTermo);
		_columnOriginalValues.put("arquivoPdf", _arquivoPdf);
		_columnOriginalValues.put("parte", _parte);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("termoId", 2L);

		columnBitmasks.put("propostaId", 4L);

		columnBitmasks.put("urlTermo", 8L);

		columnBitmasks.put("arquivoPdf", 16L);

		columnBitmasks.put("parte", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TermoAssinado _escapedModel;

}