/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AcaoJudicialProposta service. Represents a row in the &quot;GDF_AcaoJudicialProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.AcaoJudicialPropostaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.AcaoJudicialPropostaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AcaoJudicialProposta
 * @generated
 */
@ProviderType
public interface AcaoJudicialPropostaModel
	extends BaseModel<AcaoJudicialProposta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a acao judicial proposta model instance should use the {@link AcaoJudicialProposta} interface instead.
	 */

	/**
	 * Returns the primary key of this acao judicial proposta.
	 *
	 * @return the primary key of this acao judicial proposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this acao judicial proposta.
	 *
	 * @param primaryKey the primary key of this acao judicial proposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this acao judicial proposta.
	 *
	 * @return the uuid of this acao judicial proposta
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this acao judicial proposta.
	 *
	 * @param uuid the uuid of this acao judicial proposta
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the acao proposta ID of this acao judicial proposta.
	 *
	 * @return the acao proposta ID of this acao judicial proposta
	 */
	public long getAcaoPropostaId();

	/**
	 * Sets the acao proposta ID of this acao judicial proposta.
	 *
	 * @param acaoPropostaId the acao proposta ID of this acao judicial proposta
	 */
	public void setAcaoPropostaId(long acaoPropostaId);

	/**
	 * Returns the proposta ID of this acao judicial proposta.
	 *
	 * @return the proposta ID of this acao judicial proposta
	 */
	public long getPropostaId();

	/**
	 * Sets the proposta ID of this acao judicial proposta.
	 *
	 * @param propostaId the proposta ID of this acao judicial proposta
	 */
	public void setPropostaId(long propostaId);

	/**
	 * Returns the acao ID of this acao judicial proposta.
	 *
	 * @return the acao ID of this acao judicial proposta
	 */
	public long getAcaoId();

	/**
	 * Sets the acao ID of this acao judicial proposta.
	 *
	 * @param acaoId the acao ID of this acao judicial proposta
	 */
	public void setAcaoId(long acaoId);

	@Override
	public AcaoJudicialProposta cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}