/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ComprovanteHonorario service. Represents a row in the &quot;GDF_ComprovanteHonorario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.ComprovanteHonorarioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.ComprovanteHonorarioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComprovanteHonorario
 * @generated
 */
@ProviderType
public interface ComprovanteHonorarioModel
	extends BaseModel<ComprovanteHonorario> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comprovante honorario model instance should use the {@link ComprovanteHonorario} interface instead.
	 */

	/**
	 * Returns the primary key of this comprovante honorario.
	 *
	 * @return the primary key of this comprovante honorario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comprovante honorario.
	 *
	 * @param primaryKey the primary key of this comprovante honorario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this comprovante honorario.
	 *
	 * @return the uuid of this comprovante honorario
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this comprovante honorario.
	 *
	 * @param uuid the uuid of this comprovante honorario
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the comprovante ID of this comprovante honorario.
	 *
	 * @return the comprovante ID of this comprovante honorario
	 */
	public long getComprovanteId();

	/**
	 * Sets the comprovante ID of this comprovante honorario.
	 *
	 * @param comprovanteId the comprovante ID of this comprovante honorario
	 */
	public void setComprovanteId(long comprovanteId);

	/**
	 * Returns the proposta ID of this comprovante honorario.
	 *
	 * @return the proposta ID of this comprovante honorario
	 */
	public long getPropostaId();

	/**
	 * Sets the proposta ID of this comprovante honorario.
	 *
	 * @param propostaId the proposta ID of this comprovante honorario
	 */
	public void setPropostaId(long propostaId);

	/**
	 * Returns the valor pago of this comprovante honorario.
	 *
	 * @return the valor pago of this comprovante honorario
	 */
	public double getValorPago();

	/**
	 * Sets the valor pago of this comprovante honorario.
	 *
	 * @param valorPago the valor pago of this comprovante honorario
	 */
	public void setValorPago(double valorPago);

	/**
	 * Returns the data pagamento of this comprovante honorario.
	 *
	 * @return the data pagamento of this comprovante honorario
	 */
	public Date getDataPagamento();

	/**
	 * Sets the data pagamento of this comprovante honorario.
	 *
	 * @param dataPagamento the data pagamento of this comprovante honorario
	 */
	public void setDataPagamento(Date dataPagamento);

	/**
	 * Returns the file entry ID of this comprovante honorario.
	 *
	 * @return the file entry ID of this comprovante honorario
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this comprovante honorario.
	 *
	 * @param fileEntryId the file entry ID of this comprovante honorario
	 */
	public void setFileEntryId(long fileEntryId);

	@Override
	public ComprovanteHonorario cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}