/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CreditoTransacionado service. Represents a row in the &quot;GDF_CreditoTransacionado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.CreditoTransacionadoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.CreditoTransacionadoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CreditoTransacionado
 * @generated
 */
@ProviderType
public interface CreditoTransacionadoModel
	extends BaseModel<CreditoTransacionado> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a credito transacionado model instance should use the {@link CreditoTransacionado} interface instead.
	 */

	/**
	 * Returns the primary key of this credito transacionado.
	 *
	 * @return the primary key of this credito transacionado
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this credito transacionado.
	 *
	 * @param primaryKey the primary key of this credito transacionado
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this credito transacionado.
	 *
	 * @return the uuid of this credito transacionado
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this credito transacionado.
	 *
	 * @param uuid the uuid of this credito transacionado
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the credito ID of this credito transacionado.
	 *
	 * @return the credito ID of this credito transacionado
	 */
	public long getCreditoId();

	/**
	 * Sets the credito ID of this credito transacionado.
	 *
	 * @param creditoId the credito ID of this credito transacionado
	 */
	public void setCreditoId(long creditoId);

	/**
	 * Returns the proposta ID of this credito transacionado.
	 *
	 * @return the proposta ID of this credito transacionado
	 */
	public long getPropostaId();

	/**
	 * Sets the proposta ID of this credito transacionado.
	 *
	 * @param propostaId the proposta ID of this credito transacionado
	 */
	public void setPropostaId(long propostaId);

	/**
	 * Returns the numero inscricao of this credito transacionado.
	 *
	 * @return the numero inscricao of this credito transacionado
	 */
	@AutoEscape
	public String getNumeroInscricao();

	/**
	 * Sets the numero inscricao of this credito transacionado.
	 *
	 * @param numeroInscricao the numero inscricao of this credito transacionado
	 */
	public void setNumeroInscricao(String numeroInscricao);

	/**
	 * Returns the codigo receita of this credito transacionado.
	 *
	 * @return the codigo receita of this credito transacionado
	 */
	@AutoEscape
	public String getCodigoReceita();

	/**
	 * Sets the codigo receita of this credito transacionado.
	 *
	 * @param codigoReceita the codigo receita of this credito transacionado
	 */
	public void setCodigoReceita(String codigoReceita);

	/**
	 * Returns the data inscricao of this credito transacionado.
	 *
	 * @return the data inscricao of this credito transacionado
	 */
	public Date getDataInscricao();

	/**
	 * Sets the data inscricao of this credito transacionado.
	 *
	 * @param dataInscricao the data inscricao of this credito transacionado
	 */
	public void setDataInscricao(Date dataInscricao);

	/**
	 * Returns the valor atualizado of this credito transacionado.
	 *
	 * @return the valor atualizado of this credito transacionado
	 */
	public double getValorAtualizado();

	/**
	 * Sets the valor atualizado of this credito transacionado.
	 *
	 * @param valorAtualizado the valor atualizado of this credito transacionado
	 */
	public void setValorAtualizado(double valorAtualizado);

	@Override
	public CreditoTransacionado cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}