/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DemonstracaoDocumentos service. Represents a row in the &quot;GDF_DemonstracaoDocumentos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.DemonstracaoDocumentosModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.DemonstracaoDocumentosImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DemonstracaoDocumentos
 * @generated
 */
@ProviderType
public interface DemonstracaoDocumentosModel
	extends BaseModel<DemonstracaoDocumentos> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a demonstracao documentos model instance should use the {@link DemonstracaoDocumentos} interface instead.
	 */

	/**
	 * Returns the primary key of this demonstracao documentos.
	 *
	 * @return the primary key of this demonstracao documentos
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this demonstracao documentos.
	 *
	 * @param primaryKey the primary key of this demonstracao documentos
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this demonstracao documentos.
	 *
	 * @return the uuid of this demonstracao documentos
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this demonstracao documentos.
	 *
	 * @param uuid the uuid of this demonstracao documentos
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the demonstracao documentos ID of this demonstracao documentos.
	 *
	 * @return the demonstracao documentos ID of this demonstracao documentos
	 */
	public long getDemonstracaoDocumentosId();

	/**
	 * Sets the demonstracao documentos ID of this demonstracao documentos.
	 *
	 * @param demonstracaoDocumentosId the demonstracao documentos ID of this demonstracao documentos
	 */
	public void setDemonstracaoDocumentosId(long demonstracaoDocumentosId);

	/**
	 * Returns the demonstracao ID of this demonstracao documentos.
	 *
	 * @return the demonstracao ID of this demonstracao documentos
	 */
	public long getDemonstracaoId();

	/**
	 * Sets the demonstracao ID of this demonstracao documentos.
	 *
	 * @param demonstracaoId the demonstracao ID of this demonstracao documentos
	 */
	public void setDemonstracaoId(long demonstracaoId);

	/**
	 * Returns the tipo documento of this demonstracao documentos.
	 *
	 * @return the tipo documento of this demonstracao documentos
	 */
	public int getTipoDocumento();

	/**
	 * Sets the tipo documento of this demonstracao documentos.
	 *
	 * @param tipoDocumento the tipo documento of this demonstracao documentos
	 */
	public void setTipoDocumento(int tipoDocumento);

	@Override
	public DemonstracaoDocumentos cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}