/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DocumentoComprobatorio service. Represents a row in the &quot;GDF_DocumentoComprobatorio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.DocumentoComprobatorioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.DocumentoComprobatorioImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentoComprobatorio
 * @generated
 */
@ProviderType
public interface DocumentoComprobatorioModel
	extends BaseModel<DocumentoComprobatorio> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a documento comprobatorio model instance should use the {@link DocumentoComprobatorio} interface instead.
	 */

	/**
	 * Returns the primary key of this documento comprobatorio.
	 *
	 * @return the primary key of this documento comprobatorio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this documento comprobatorio.
	 *
	 * @param primaryKey the primary key of this documento comprobatorio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this documento comprobatorio.
	 *
	 * @return the uuid of this documento comprobatorio
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this documento comprobatorio.
	 *
	 * @param uuid the uuid of this documento comprobatorio
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the documento ID of this documento comprobatorio.
	 *
	 * @return the documento ID of this documento comprobatorio
	 */
	public long getDocumentoId();

	/**
	 * Sets the documento ID of this documento comprobatorio.
	 *
	 * @param documentoId the documento ID of this documento comprobatorio
	 */
	public void setDocumentoId(long documentoId);

	/**
	 * Returns the fundamentacao ID of this documento comprobatorio.
	 *
	 * @return the fundamentacao ID of this documento comprobatorio
	 */
	public long getFundamentacaoId();

	/**
	 * Sets the fundamentacao ID of this documento comprobatorio.
	 *
	 * @param fundamentacaoId the fundamentacao ID of this documento comprobatorio
	 */
	public void setFundamentacaoId(long fundamentacaoId);

	/**
	 * Returns the file entry ID of this documento comprobatorio.
	 *
	 * @return the file entry ID of this documento comprobatorio
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this documento comprobatorio.
	 *
	 * @param fileEntryId the file entry ID of this documento comprobatorio
	 */
	public void setFileEntryId(long fileEntryId);

	@Override
	public DocumentoComprobatorio cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}