/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Edital service. Represents a row in the &quot;GDF_Edital&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.EditalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.EditalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Edital
 * @generated
 */
@ProviderType
public interface EditalModel extends BaseModel<Edital> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a edital model instance should use the {@link Edital} interface instead.
	 */

	/**
	 * Returns the primary key of this edital.
	 *
	 * @return the primary key of this edital
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this edital.
	 *
	 * @param primaryKey the primary key of this edital
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this edital.
	 *
	 * @return the uuid of this edital
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this edital.
	 *
	 * @param uuid the uuid of this edital
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the edital ID of this edital.
	 *
	 * @return the edital ID of this edital
	 */
	public long getEditalId();

	/**
	 * Sets the edital ID of this edital.
	 *
	 * @param editalId the edital ID of this edital
	 */
	public void setEditalId(long editalId);

	/**
	 * Returns the titulo of this edital.
	 *
	 * @return the titulo of this edital
	 */
	@AutoEscape
	public String getTitulo();

	/**
	 * Sets the titulo of this edital.
	 *
	 * @param titulo the titulo of this edital
	 */
	public void setTitulo(String titulo);

	/**
	 * Returns the descricao of this edital.
	 *
	 * @return the descricao of this edital
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this edital.
	 *
	 * @param descricao the descricao of this edital
	 */
	public void setDescricao(String descricao);

	/**
	 * Returns the arquivo of this edital.
	 *
	 * @return the arquivo of this edital
	 */
	public long getArquivo();

	/**
	 * Sets the arquivo of this edital.
	 *
	 * @param arquivo the arquivo of this edital
	 */
	public void setArquivo(long arquivo);

	/**
	 * Returns the data inicio of this edital.
	 *
	 * @return the data inicio of this edital
	 */
	public Date getDataInicio();

	/**
	 * Sets the data inicio of this edital.
	 *
	 * @param dataInicio the data inicio of this edital
	 */
	public void setDataInicio(Date dataInicio);

	/**
	 * Returns the data fim of this edital.
	 *
	 * @return the data fim of this edital
	 */
	public Date getDataFim();

	/**
	 * Sets the data fim of this edital.
	 *
	 * @param dataFim the data fim of this edital
	 */
	public void setDataFim(Date dataFim);

	@Override
	public Edital cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}