/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GarantiaProposta service. Represents a row in the &quot;GDF_GarantiaProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.GarantiaPropostaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.GarantiaPropostaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GarantiaProposta
 * @generated
 */
@ProviderType
public interface GarantiaPropostaModel extends BaseModel<GarantiaProposta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a garantia proposta model instance should use the {@link GarantiaProposta} interface instead.
	 */

	/**
	 * Returns the primary key of this garantia proposta.
	 *
	 * @return the primary key of this garantia proposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this garantia proposta.
	 *
	 * @param primaryKey the primary key of this garantia proposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this garantia proposta.
	 *
	 * @return the uuid of this garantia proposta
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this garantia proposta.
	 *
	 * @param uuid the uuid of this garantia proposta
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the garantia proposta ID of this garantia proposta.
	 *
	 * @return the garantia proposta ID of this garantia proposta
	 */
	public long getGarantiaPropostaId();

	/**
	 * Sets the garantia proposta ID of this garantia proposta.
	 *
	 * @param garantiaPropostaId the garantia proposta ID of this garantia proposta
	 */
	public void setGarantiaPropostaId(long garantiaPropostaId);

	/**
	 * Returns the proposta ID of this garantia proposta.
	 *
	 * @return the proposta ID of this garantia proposta
	 */
	public long getPropostaId();

	/**
	 * Sets the proposta ID of this garantia proposta.
	 *
	 * @param propostaId the proposta ID of this garantia proposta
	 */
	public void setPropostaId(long propostaId);

	/**
	 * Returns the garantia ID of this garantia proposta.
	 *
	 * @return the garantia ID of this garantia proposta
	 */
	public long getGarantiaId();

	/**
	 * Sets the garantia ID of this garantia proposta.
	 *
	 * @param garantiaId the garantia ID of this garantia proposta
	 */
	public void setGarantiaId(long garantiaId);

	@Override
	public GarantiaProposta cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}