/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IdentificacaoDebitos service. Represents a row in the &quot;GDF_IdentificacaoDebitos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.IdentificacaoDebitosModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.IdentificacaoDebitosImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IdentificacaoDebitos
 * @generated
 */
@ProviderType
public interface IdentificacaoDebitosModel
	extends BaseModel<IdentificacaoDebitos> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a identificacao debitos model instance should use the {@link IdentificacaoDebitos} interface instead.
	 */

	/**
	 * Returns the primary key of this identificacao debitos.
	 *
	 * @return the primary key of this identificacao debitos
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this identificacao debitos.
	 *
	 * @param primaryKey the primary key of this identificacao debitos
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this identificacao debitos.
	 *
	 * @return the uuid of this identificacao debitos
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this identificacao debitos.
	 *
	 * @param uuid the uuid of this identificacao debitos
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the identificacao debitos ID of this identificacao debitos.
	 *
	 * @return the identificacao debitos ID of this identificacao debitos
	 */
	public long getIdentificacaoDebitosId();

	/**
	 * Sets the identificacao debitos ID of this identificacao debitos.
	 *
	 * @param identificacaoDebitosId the identificacao debitos ID of this identificacao debitos
	 */
	public void setIdentificacaoDebitosId(long identificacaoDebitosId);

	/**
	 * Returns the fundamentacao ID of this identificacao debitos.
	 *
	 * @return the fundamentacao ID of this identificacao debitos
	 */
	public long getFundamentacaoId();

	/**
	 * Sets the fundamentacao ID of this identificacao debitos.
	 *
	 * @param fundamentacaoId the fundamentacao ID of this identificacao debitos
	 */
	public void setFundamentacaoId(long fundamentacaoId);

	/**
	 * Returns the natureza of this identificacao debitos.
	 *
	 * @return the natureza of this identificacao debitos
	 */
	@AutoEscape
	public String getNatureza();

	/**
	 * Sets the natureza of this identificacao debitos.
	 *
	 * @param natureza the natureza of this identificacao debitos
	 */
	public void setNatureza(String natureza);

	/**
	 * Returns the situacao of this identificacao debitos.
	 *
	 * @return the situacao of this identificacao debitos
	 */
	@AutoEscape
	public String getSituacao();

	/**
	 * Sets the situacao of this identificacao debitos.
	 *
	 * @param situacao the situacao of this identificacao debitos
	 */
	public void setSituacao(String situacao);

	/**
	 * Returns the inscricao divida ativa of this identificacao debitos.
	 *
	 * @return the inscricao divida ativa of this identificacao debitos
	 */
	@AutoEscape
	public String getInscricaoDividaAtiva();

	/**
	 * Sets the inscricao divida ativa of this identificacao debitos.
	 *
	 * @param inscricaoDividaAtiva the inscricao divida ativa of this identificacao debitos
	 */
	public void setInscricaoDividaAtiva(String inscricaoDividaAtiva);

	/**
	 * Returns the garantido judicialmente of this identificacao debitos.
	 *
	 * @return the garantido judicialmente of this identificacao debitos
	 */
	@AutoEscape
	public String getGarantidoJudicialmente();

	/**
	 * Sets the garantido judicialmente of this identificacao debitos.
	 *
	 * @param garantidoJudicialmente the garantido judicialmente of this identificacao debitos
	 */
	public void setGarantidoJudicialmente(String garantidoJudicialmente);

	@Override
	public IdentificacaoDebitos cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}