/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Proposta service. Represents a row in the &quot;GDF_Proposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.PropostaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.PropostaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Proposta
 * @generated
 */
@ProviderType
public interface PropostaModel
	extends BaseModel<Proposta>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposta model instance should use the {@link Proposta} interface instead.
	 */

	/**
	 * Returns the primary key of this proposta.
	 *
	 * @return the primary key of this proposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposta.
	 *
	 * @param primaryKey the primary key of this proposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this proposta.
	 *
	 * @return the uuid of this proposta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this proposta.
	 *
	 * @param uuid the uuid of this proposta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the proposta ID of this proposta.
	 *
	 * @return the proposta ID of this proposta
	 */
	public long getPropostaId();

	/**
	 * Sets the proposta ID of this proposta.
	 *
	 * @param propostaId the proposta ID of this proposta
	 */
	public void setPropostaId(long propostaId);

	/**
	 * Returns the group ID of this proposta.
	 *
	 * @return the group ID of this proposta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this proposta.
	 *
	 * @param groupId the group ID of this proposta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this proposta.
	 *
	 * @return the company ID of this proposta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this proposta.
	 *
	 * @param companyId the company ID of this proposta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this proposta.
	 *
	 * @return the user ID of this proposta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this proposta.
	 *
	 * @param userId the user ID of this proposta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this proposta.
	 *
	 * @return the user uuid of this proposta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this proposta.
	 *
	 * @param userUuid the user uuid of this proposta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this proposta.
	 *
	 * @return the user name of this proposta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this proposta.
	 *
	 * @param userName the user name of this proposta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this proposta.
	 *
	 * @return the create date of this proposta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this proposta.
	 *
	 * @param createDate the create date of this proposta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this proposta.
	 *
	 * @return the modified date of this proposta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this proposta.
	 *
	 * @param modifiedDate the modified date of this proposta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tipo proposta of this proposta.
	 *
	 * @return the tipo proposta of this proposta
	 */
	@AutoEscape
	public String getTipoProposta();

	/**
	 * Sets the tipo proposta of this proposta.
	 *
	 * @param tipoProposta the tipo proposta of this proposta
	 */
	public void setTipoProposta(String tipoProposta);

	/**
	 * Returns the edital ID of this proposta.
	 *
	 * @return the edital ID of this proposta
	 */
	public long getEditalId();

	/**
	 * Sets the edital ID of this proposta.
	 *
	 * @param editalId the edital ID of this proposta
	 */
	public void setEditalId(long editalId);

	/**
	 * Returns the qualificacao ID of this proposta.
	 *
	 * @return the qualificacao ID of this proposta
	 */
	public long getQualificacaoId();

	/**
	 * Sets the qualificacao ID of this proposta.
	 *
	 * @param qualificacaoId the qualificacao ID of this proposta
	 */
	public void setQualificacaoId(long qualificacaoId);

	/**
	 * Returns the administrador judicial ID of this proposta.
	 *
	 * @return the administrador judicial ID of this proposta
	 */
	public long getAdministradorJudicialId();

	/**
	 * Sets the administrador judicial ID of this proposta.
	 *
	 * @param administradorJudicialId the administrador judicial ID of this proposta
	 */
	public void setAdministradorJudicialId(long administradorJudicialId);

	/**
	 * Returns the advogado ID of this proposta.
	 *
	 * @return the advogado ID of this proposta
	 */
	public long getAdvogadoId();

	/**
	 * Sets the advogado ID of this proposta.
	 *
	 * @param advogadoId the advogado ID of this proposta
	 */
	public void setAdvogadoId(long advogadoId);

	/**
	 * Returns the fundamentacao pedido ID of this proposta.
	 *
	 * @return the fundamentacao pedido ID of this proposta
	 */
	public long getFundamentacaoPedidoId();

	/**
	 * Sets the fundamentacao pedido ID of this proposta.
	 *
	 * @param fundamentacaoPedidoId the fundamentacao pedido ID of this proposta
	 */
	public void setFundamentacaoPedidoId(long fundamentacaoPedidoId);

	/**
	 * Returns the procuracao of this proposta.
	 *
	 * @return the procuracao of this proposta
	 */
	public long getProcuracao();

	/**
	 * Sets the procuracao of this proposta.
	 *
	 * @param procuracao the procuracao of this proposta
	 */
	public void setProcuracao(long procuracao);

	/**
	 * Returns the cpf cnpj of this proposta.
	 *
	 * @return the cpf cnpj of this proposta
	 */
	@AutoEscape
	public String getCpfCnpj();

	/**
	 * Sets the cpf cnpj of this proposta.
	 *
	 * @param cpfCnpj the cpf cnpj of this proposta
	 */
	public void setCpfCnpj(String cpfCnpj);

	/**
	 * Returns the status of this proposta.
	 *
	 * @return the status of this proposta
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this proposta.
	 *
	 * @param status the status of this proposta
	 */
	public void setStatus(String status);

	/**
	 * Returns the numero protocolo sei of this proposta.
	 *
	 * @return the numero protocolo sei of this proposta
	 */
	@AutoEscape
	public String getNumeroProtocoloSei();

	/**
	 * Sets the numero protocolo sei of this proposta.
	 *
	 * @param numeroProtocoloSei the numero protocolo sei of this proposta
	 */
	public void setNumeroProtocoloSei(String numeroProtocoloSei);

	/**
	 * Returns the protocolo of this proposta.
	 *
	 * @return the protocolo of this proposta
	 */
	@AutoEscape
	public String getProtocolo();

	/**
	 * Sets the protocolo of this proposta.
	 *
	 * @param protocolo the protocolo of this proposta
	 */
	public void setProtocolo(String protocolo);

	/**
	 * Returns the documentos completos url of this proposta.
	 *
	 * @return the documentos completos url of this proposta
	 */
	@AutoEscape
	public String getDocumentosCompletosURL();

	/**
	 * Sets the documentos completos url of this proposta.
	 *
	 * @param documentosCompletosURL the documentos completos url of this proposta
	 */
	public void setDocumentosCompletosURL(String documentosCompletosURL);

	/**
	 * Returns the proposta pai ID of this proposta.
	 *
	 * @return the proposta pai ID of this proposta
	 */
	public long getPropostaPaiId();

	/**
	 * Sets the proposta pai ID of this proposta.
	 *
	 * @param propostaPaiId the proposta pai ID of this proposta
	 */
	public void setPropostaPaiId(long propostaPaiId);

	@Override
	public Proposta cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}