/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the QualificacaoContribuinte service. Represents a row in the &quot;GDF_QualificacaoContribuinte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.QualificacaoContribuinteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.QualificacaoContribuinteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QualificacaoContribuinte
 * @generated
 */
@ProviderType
public interface QualificacaoContribuinteModel
	extends BaseModel<QualificacaoContribuinte>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qualificacao contribuinte model instance should use the {@link QualificacaoContribuinte} interface instead.
	 */

	/**
	 * Returns the primary key of this qualificacao contribuinte.
	 *
	 * @return the primary key of this qualificacao contribuinte
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qualificacao contribuinte.
	 *
	 * @param primaryKey the primary key of this qualificacao contribuinte
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this qualificacao contribuinte.
	 *
	 * @return the uuid of this qualificacao contribuinte
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this qualificacao contribuinte.
	 *
	 * @param uuid the uuid of this qualificacao contribuinte
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the qualificacao contribuinte ID of this qualificacao contribuinte.
	 *
	 * @return the qualificacao contribuinte ID of this qualificacao contribuinte
	 */
	public long getQualificacaoContribuinteId();

	/**
	 * Sets the qualificacao contribuinte ID of this qualificacao contribuinte.
	 *
	 * @param qualificacaoContribuinteId the qualificacao contribuinte ID of this qualificacao contribuinte
	 */
	public void setQualificacaoContribuinteId(long qualificacaoContribuinteId);

	/**
	 * Returns the dados contribuinte ID of this qualificacao contribuinte.
	 *
	 * @return the dados contribuinte ID of this qualificacao contribuinte
	 */
	public long getDadosContribuinteId();

	/**
	 * Sets the dados contribuinte ID of this qualificacao contribuinte.
	 *
	 * @param dadosContribuinteId the dados contribuinte ID of this qualificacao contribuinte
	 */
	public void setDadosContribuinteId(long dadosContribuinteId);

	/**
	 * Returns the qualificacao ID of this qualificacao contribuinte.
	 *
	 * @return the qualificacao ID of this qualificacao contribuinte
	 */
	public long getQualificacaoId();

	/**
	 * Sets the qualificacao ID of this qualificacao contribuinte.
	 *
	 * @param qualificacaoId the qualificacao ID of this qualificacao contribuinte
	 */
	public void setQualificacaoId(long qualificacaoId);

	/**
	 * Returns the create date of this qualificacao contribuinte.
	 *
	 * @return the create date of this qualificacao contribuinte
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this qualificacao contribuinte.
	 *
	 * @param createDate the create date of this qualificacao contribuinte
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this qualificacao contribuinte.
	 *
	 * @return the modified date of this qualificacao contribuinte
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qualificacao contribuinte.
	 *
	 * @param modifiedDate the modified date of this qualificacao contribuinte
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this qualificacao contribuinte.
	 *
	 * @return the user ID of this qualificacao contribuinte
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this qualificacao contribuinte.
	 *
	 * @param userId the user ID of this qualificacao contribuinte
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this qualificacao contribuinte.
	 *
	 * @return the user uuid of this qualificacao contribuinte
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this qualificacao contribuinte.
	 *
	 * @param userUuid the user uuid of this qualificacao contribuinte
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this qualificacao contribuinte.
	 *
	 * @return the group ID of this qualificacao contribuinte
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this qualificacao contribuinte.
	 *
	 * @param groupId the group ID of this qualificacao contribuinte
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this qualificacao contribuinte.
	 *
	 * @return the company ID of this qualificacao contribuinte
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this qualificacao contribuinte.
	 *
	 * @param companyId the company ID of this qualificacao contribuinte
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the tipo qualificacao of this qualificacao contribuinte.
	 *
	 * @return the tipo qualificacao of this qualificacao contribuinte
	 */
	@AutoEscape
	public String getTipoQualificacao();

	/**
	 * Sets the tipo qualificacao of this qualificacao contribuinte.
	 *
	 * @param tipoQualificacao the tipo qualificacao of this qualificacao contribuinte
	 */
	public void setTipoQualificacao(String tipoQualificacao);

	@Override
	public QualificacaoContribuinte cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}