/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.gdf.negocia.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the QualificacaoCompleta service. Represents a row in the &quot;GDF_QualificacaoCompleta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.gdf.negocia.model.impl.QualificacaoCompletaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.gdf.negocia.model.impl.QualificacaoCompletaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see QualificacaoCompleta
 * @generated
 */
@ProviderType
public interface QualificacaoCompletaModel
	extends BaseModel<QualificacaoCompleta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qualificacao completa model instance should use the {@link QualificacaoCompleta} interface instead.
	 */

	/**
	 * Returns the primary key of this qualificacao completa.
	 *
	 * @return the primary key of this qualificacao completa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qualificacao completa.
	 *
	 * @param primaryKey the primary key of this qualificacao completa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this qualificacao completa.
	 *
	 * @return the uuid of this qualificacao completa
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this qualificacao completa.
	 *
	 * @param uuid the uuid of this qualificacao completa
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the qualificacao ID of this qualificacao completa.
	 *
	 * @return the qualificacao ID of this qualificacao completa
	 */
	public long getQualificacaoId();

	/**
	 * Sets the qualificacao ID of this qualificacao completa.
	 *
	 * @param qualificacaoId the qualificacao ID of this qualificacao completa
	 */
	public void setQualificacaoId(long qualificacaoId);

	/**
	 * Returns the tipo pessoa of this qualificacao completa.
	 *
	 * @return the tipo pessoa of this qualificacao completa
	 */
	@AutoEscape
	public String getTipoPessoa();

	/**
	 * Sets the tipo pessoa of this qualificacao completa.
	 *
	 * @param tipoPessoa the tipo pessoa of this qualificacao completa
	 */
	public void setTipoPessoa(String tipoPessoa);

	/**
	 * Returns the nome razao social of this qualificacao completa.
	 *
	 * @return the nome razao social of this qualificacao completa
	 */
	@AutoEscape
	public String getNomeRazaoSocial();

	/**
	 * Sets the nome razao social of this qualificacao completa.
	 *
	 * @param nomeRazaoSocial the nome razao social of this qualificacao completa
	 */
	public void setNomeRazaoSocial(String nomeRazaoSocial);

	/**
	 * Returns the nome fantasia of this qualificacao completa.
	 *
	 * @return the nome fantasia of this qualificacao completa
	 */
	@AutoEscape
	public String getNomeFantasia();

	/**
	 * Sets the nome fantasia of this qualificacao completa.
	 *
	 * @param nomeFantasia the nome fantasia of this qualificacao completa
	 */
	public void setNomeFantasia(String nomeFantasia);

	/**
	 * Returns the representante legal of this qualificacao completa.
	 *
	 * @return the representante legal of this qualificacao completa
	 */
	@AutoEscape
	public String getRepresentanteLegal();

	/**
	 * Sets the representante legal of this qualificacao completa.
	 *
	 * @param representanteLegal the representante legal of this qualificacao completa
	 */
	public void setRepresentanteLegal(String representanteLegal);

	/**
	 * Returns the cpf cnpj of this qualificacao completa.
	 *
	 * @return the cpf cnpj of this qualificacao completa
	 */
	@AutoEscape
	public String getCpfCnpj();

	/**
	 * Sets the cpf cnpj of this qualificacao completa.
	 *
	 * @param cpfCnpj the cpf cnpj of this qualificacao completa
	 */
	public void setCpfCnpj(String cpfCnpj);

	/**
	 * Returns the domicilio fiscal of this qualificacao completa.
	 *
	 * @return the domicilio fiscal of this qualificacao completa
	 */
	@AutoEscape
	public String getDomicilioFiscal();

	/**
	 * Sets the domicilio fiscal of this qualificacao completa.
	 *
	 * @param domicilioFiscal the domicilio fiscal of this qualificacao completa
	 */
	public void setDomicilioFiscal(String domicilioFiscal);

	/**
	 * Returns the numero cfdf of this qualificacao completa.
	 *
	 * @return the numero cfdf of this qualificacao completa
	 */
	@AutoEscape
	public String getNumeroCfdf();

	/**
	 * Sets the numero cfdf of this qualificacao completa.
	 *
	 * @param numeroCfdf the numero cfdf of this qualificacao completa
	 */
	public void setNumeroCfdf(String numeroCfdf);

	/**
	 * Returns the email of this qualificacao completa.
	 *
	 * @return the email of this qualificacao completa
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this qualificacao completa.
	 *
	 * @param email the email of this qualificacao completa
	 */
	public void setEmail(String email);

	/**
	 * Returns the telefone of this qualificacao completa.
	 *
	 * @return the telefone of this qualificacao completa
	 */
	@AutoEscape
	public String getTelefone();

	/**
	 * Sets the telefone of this qualificacao completa.
	 *
	 * @param telefone the telefone of this qualificacao completa
	 */
	public void setTelefone(String telefone);

	/**
	 * Returns the whatsapp of this qualificacao completa.
	 *
	 * @return the whatsapp of this qualificacao completa
	 */
	@AutoEscape
	public String getWhatsapp();

	/**
	 * Sets the whatsapp of this qualificacao completa.
	 *
	 * @param whatsapp the whatsapp of this qualificacao completa
	 */
	public void setWhatsapp(String whatsapp);

	/**
	 * Returns the endereco postal ID of this qualificacao completa.
	 *
	 * @return the endereco postal ID of this qualificacao completa
	 */
	public long getEnderecoPostalId();

	/**
	 * Sets the endereco postal ID of this qualificacao completa.
	 *
	 * @param enderecoPostalId the endereco postal ID of this qualificacao completa
	 */
	public void setEnderecoPostalId(long enderecoPostalId);

	@Override
	public QualificacaoCompleta cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}