/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.article.lock.model.impl;

import com.example.article.lock.model.ArticleEditLock;
import com.example.article.lock.model.ArticleEditLockModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ArticleEditLock service. Represents a row in the &quot;ArticleLock_ArticleEditLock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ArticleEditLockModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ArticleEditLockImpl}.
 * </p>
 *
 * @author Nicollas Rezende
 * @see ArticleEditLockImpl
 * @generated
 */
public class ArticleEditLockModelImpl
	extends BaseModelImpl<ArticleEditLock> implements ArticleEditLockModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a article edit lock model instance should use the <code>ArticleEditLock</code> interface instead.
	 */
	public static final String TABLE_NAME = "ArticleLock_ArticleEditLock";

	public static final Object[][] TABLE_COLUMNS = {
		{"articleEditLockId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"articleId", Types.VARCHAR},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"userFullName", Types.VARCHAR}, {"locked", Types.BOOLEAN},
		{"lockTime", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("articleEditLockId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("articleId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userFullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("locked", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("lockTime", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ArticleLock_ArticleEditLock (articleEditLockId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,articleId VARCHAR(75) null,userId LONG,userName VARCHAR(75) null,userFullName VARCHAR(75) null,locked BOOLEAN,lockTime DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ArticleLock_ArticleEditLock";

	public static final String ORDER_BY_JPQL =
		" ORDER BY articleEditLock.articleEditLockId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ArticleLock_ArticleEditLock.articleEditLockId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ARTICLEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCKTIME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCKED_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ARTICLEEDITLOCKID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ArticleEditLockModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _articleEditLockId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setArticleEditLockId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _articleEditLockId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ArticleEditLock.class;
	}

	@Override
	public String getModelClassName() {
		return ArticleEditLock.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ArticleEditLock, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ArticleEditLock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArticleEditLock, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ArticleEditLock)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ArticleEditLock, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ArticleEditLock, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ArticleEditLock)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ArticleEditLock, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ArticleEditLock, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ArticleEditLock, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ArticleEditLock, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ArticleEditLock, Object>>();

			attributeGetterFunctions.put(
				"articleEditLockId", ArticleEditLock::getArticleEditLockId);
			attributeGetterFunctions.put(
				"companyId", ArticleEditLock::getCompanyId);
			attributeGetterFunctions.put(
				"groupId", ArticleEditLock::getGroupId);
			attributeGetterFunctions.put(
				"createDate", ArticleEditLock::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ArticleEditLock::getModifiedDate);
			attributeGetterFunctions.put(
				"articleId", ArticleEditLock::getArticleId);
			attributeGetterFunctions.put("userId", ArticleEditLock::getUserId);
			attributeGetterFunctions.put(
				"userName", ArticleEditLock::getUserName);
			attributeGetterFunctions.put(
				"userFullName", ArticleEditLock::getUserFullName);
			attributeGetterFunctions.put("locked", ArticleEditLock::getLocked);
			attributeGetterFunctions.put(
				"lockTime", ArticleEditLock::getLockTime);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ArticleEditLock, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ArticleEditLock, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ArticleEditLock, ?>>();

			attributeSetterBiConsumers.put(
				"articleEditLockId",
				(BiConsumer<ArticleEditLock, Long>)
					ArticleEditLock::setArticleEditLockId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ArticleEditLock, Long>)
					ArticleEditLock::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ArticleEditLock, Long>)ArticleEditLock::setGroupId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ArticleEditLock, Date>)
					ArticleEditLock::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ArticleEditLock, Date>)
					ArticleEditLock::setModifiedDate);
			attributeSetterBiConsumers.put(
				"articleId",
				(BiConsumer<ArticleEditLock, String>)
					ArticleEditLock::setArticleId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ArticleEditLock, Long>)ArticleEditLock::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ArticleEditLock, String>)
					ArticleEditLock::setUserName);
			attributeSetterBiConsumers.put(
				"userFullName",
				(BiConsumer<ArticleEditLock, String>)
					ArticleEditLock::setUserFullName);
			attributeSetterBiConsumers.put(
				"locked",
				(BiConsumer<ArticleEditLock, Boolean>)
					ArticleEditLock::setLocked);
			attributeSetterBiConsumers.put(
				"lockTime",
				(BiConsumer<ArticleEditLock, Date>)
					ArticleEditLock::setLockTime);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getArticleEditLockId() {
		return _articleEditLockId;
	}

	@Override
	public void setArticleEditLockId(long articleEditLockId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleEditLockId = articleEditLockId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return "";
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleId = articleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalArticleId() {
		return getColumnOriginalValue("articleId");
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public String getUserFullName() {
		if (_userFullName == null) {
			return "";
		}
		else {
			return _userFullName;
		}
	}

	@Override
	public void setUserFullName(String userFullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userFullName = userFullName;
	}

	@Override
	public boolean getLocked() {
		return _locked;
	}

	@Override
	public boolean isLocked() {
		return _locked;
	}

	@Override
	public void setLocked(boolean locked) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_locked = locked;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalLocked() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("locked"));
	}

	@Override
	public Date getLockTime() {
		return _lockTime;
	}

	@Override
	public void setLockTime(Date lockTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lockTime = lockTime;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalLockTime() {
		return getColumnOriginalValue("lockTime");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ArticleEditLock.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ArticleEditLock toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ArticleEditLock>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ArticleEditLockImpl articleEditLockImpl = new ArticleEditLockImpl();

		articleEditLockImpl.setArticleEditLockId(getArticleEditLockId());
		articleEditLockImpl.setCompanyId(getCompanyId());
		articleEditLockImpl.setGroupId(getGroupId());
		articleEditLockImpl.setCreateDate(getCreateDate());
		articleEditLockImpl.setModifiedDate(getModifiedDate());
		articleEditLockImpl.setArticleId(getArticleId());
		articleEditLockImpl.setUserId(getUserId());
		articleEditLockImpl.setUserName(getUserName());
		articleEditLockImpl.setUserFullName(getUserFullName());
		articleEditLockImpl.setLocked(isLocked());
		articleEditLockImpl.setLockTime(getLockTime());

		articleEditLockImpl.resetOriginalValues();

		return articleEditLockImpl;
	}

	@Override
	public ArticleEditLock cloneWithOriginalValues() {
		ArticleEditLockImpl articleEditLockImpl = new ArticleEditLockImpl();

		articleEditLockImpl.setArticleEditLockId(
			this.<Long>getColumnOriginalValue("articleEditLockId"));
		articleEditLockImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		articleEditLockImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		articleEditLockImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		articleEditLockImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		articleEditLockImpl.setArticleId(
			this.<String>getColumnOriginalValue("articleId"));
		articleEditLockImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		articleEditLockImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		articleEditLockImpl.setUserFullName(
			this.<String>getColumnOriginalValue("userFullName"));
		articleEditLockImpl.setLocked(
			this.<Boolean>getColumnOriginalValue("locked"));
		articleEditLockImpl.setLockTime(
			this.<Date>getColumnOriginalValue("lockTime"));

		return articleEditLockImpl;
	}

	@Override
	public int compareTo(ArticleEditLock articleEditLock) {
		long primaryKey = articleEditLock.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ArticleEditLock)) {
			return false;
		}

		ArticleEditLock articleEditLock = (ArticleEditLock)object;

		long primaryKey = articleEditLock.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ArticleEditLock> toCacheModel() {
		ArticleEditLockCacheModel articleEditLockCacheModel =
			new ArticleEditLockCacheModel();

		articleEditLockCacheModel.articleEditLockId = getArticleEditLockId();

		articleEditLockCacheModel.companyId = getCompanyId();

		articleEditLockCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			articleEditLockCacheModel.createDate = createDate.getTime();
		}
		else {
			articleEditLockCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			articleEditLockCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			articleEditLockCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		articleEditLockCacheModel.articleId = getArticleId();

		String articleId = articleEditLockCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			articleEditLockCacheModel.articleId = null;
		}

		articleEditLockCacheModel.userId = getUserId();

		articleEditLockCacheModel.userName = getUserName();

		String userName = articleEditLockCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			articleEditLockCacheModel.userName = null;
		}

		articleEditLockCacheModel.userFullName = getUserFullName();

		String userFullName = articleEditLockCacheModel.userFullName;

		if ((userFullName != null) && (userFullName.length() == 0)) {
			articleEditLockCacheModel.userFullName = null;
		}

		articleEditLockCacheModel.locked = isLocked();

		Date lockTime = getLockTime();

		if (lockTime != null) {
			articleEditLockCacheModel.lockTime = lockTime.getTime();
		}
		else {
			articleEditLockCacheModel.lockTime = Long.MIN_VALUE;
		}

		return articleEditLockCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ArticleEditLock, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ArticleEditLock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ArticleEditLock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ArticleEditLock)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ArticleEditLock>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ArticleEditLock.class, ModelWrapper.class);

	}

	private long _articleEditLockId;
	private long _companyId;
	private long _groupId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _articleId;
	private long _userId;
	private String _userName;
	private String _userFullName;
	private boolean _locked;
	private Date _lockTime;

	public <T> T getColumnValue(String columnName) {
		Function<ArticleEditLock, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ArticleEditLock)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("articleEditLockId", _articleEditLockId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("articleId", _articleId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("userFullName", _userFullName);
		_columnOriginalValues.put("locked", _locked);
		_columnOriginalValues.put("lockTime", _lockTime);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("articleEditLockId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("articleId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("userFullName", 256L);

		columnBitmasks.put("locked", 512L);

		columnBitmasks.put("lockTime", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ArticleEditLock _escapedModel;

}